// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module face_accelerate_conv2d_layer_Pipeline_LOAD_TILE_VITIS_LOOP_85_3_VITIS_LOOP_86_4_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY,
        m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY,
        m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST,
        m_axi_gmem0_WID,
        m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST,
        m_axi_gmem0_RID,
        m_axi_gmem0_RFIFONUM,
        m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID,
        m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP,
        m_axi_gmem0_BID,
        m_axi_gmem0_BUSER,
        zext_ln73,
        input_tile_address0,
        input_tile_ce0,
        input_tile_we0,
        input_tile_d0,
        input_tile_9_address0,
        input_tile_9_ce0,
        input_tile_9_we0,
        input_tile_9_d0,
        input_tile_10_address0,
        input_tile_10_ce0,
        input_tile_10_we0,
        input_tile_10_d0,
        input_tile_11_address0,
        input_tile_11_ce0,
        input_tile_11_we0,
        input_tile_11_d0,
        input_tile_12_address0,
        input_tile_12_ce0,
        input_tile_12_we0,
        input_tile_12_d0,
        input_tile_13_address0,
        input_tile_13_ce0,
        input_tile_13_we0,
        input_tile_13_d0,
        input_tile_14_address0,
        input_tile_14_ce0,
        input_tile_14_we0,
        input_tile_14_d0,
        input_tile_15_address0,
        input_tile_15_ce0,
        input_tile_15_we0,
        input_tile_15_d0,
        input_tile_16_address0,
        input_tile_16_ce0,
        input_tile_16_we0,
        input_tile_16_d0,
        zext_ln84,
        input_r
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem0_AWVALID;
input   m_axi_gmem0_AWREADY;
output  [63:0] m_axi_gmem0_AWADDR;
output  [0:0] m_axi_gmem0_AWID;
output  [31:0] m_axi_gmem0_AWLEN;
output  [2:0] m_axi_gmem0_AWSIZE;
output  [1:0] m_axi_gmem0_AWBURST;
output  [1:0] m_axi_gmem0_AWLOCK;
output  [3:0] m_axi_gmem0_AWCACHE;
output  [2:0] m_axi_gmem0_AWPROT;
output  [3:0] m_axi_gmem0_AWQOS;
output  [3:0] m_axi_gmem0_AWREGION;
output  [0:0] m_axi_gmem0_AWUSER;
output   m_axi_gmem0_WVALID;
input   m_axi_gmem0_WREADY;
output  [15:0] m_axi_gmem0_WDATA;
output  [1:0] m_axi_gmem0_WSTRB;
output   m_axi_gmem0_WLAST;
output  [0:0] m_axi_gmem0_WID;
output  [0:0] m_axi_gmem0_WUSER;
output   m_axi_gmem0_ARVALID;
input   m_axi_gmem0_ARREADY;
output  [63:0] m_axi_gmem0_ARADDR;
output  [0:0] m_axi_gmem0_ARID;
output  [31:0] m_axi_gmem0_ARLEN;
output  [2:0] m_axi_gmem0_ARSIZE;
output  [1:0] m_axi_gmem0_ARBURST;
output  [1:0] m_axi_gmem0_ARLOCK;
output  [3:0] m_axi_gmem0_ARCACHE;
output  [2:0] m_axi_gmem0_ARPROT;
output  [3:0] m_axi_gmem0_ARQOS;
output  [3:0] m_axi_gmem0_ARREGION;
output  [0:0] m_axi_gmem0_ARUSER;
input   m_axi_gmem0_RVALID;
output   m_axi_gmem0_RREADY;
input  [15:0] m_axi_gmem0_RDATA;
input   m_axi_gmem0_RLAST;
input  [0:0] m_axi_gmem0_RID;
input  [9:0] m_axi_gmem0_RFIFONUM;
input  [0:0] m_axi_gmem0_RUSER;
input  [1:0] m_axi_gmem0_RRESP;
input   m_axi_gmem0_BVALID;
output   m_axi_gmem0_BREADY;
input  [1:0] m_axi_gmem0_BRESP;
input  [0:0] m_axi_gmem0_BID;
input  [0:0] m_axi_gmem0_BUSER;
input  [8:0] zext_ln73;
output  [4:0] input_tile_address0;
output   input_tile_ce0;
output   input_tile_we0;
output  [15:0] input_tile_d0;
output  [4:0] input_tile_9_address0;
output   input_tile_9_ce0;
output   input_tile_9_we0;
output  [15:0] input_tile_9_d0;
output  [4:0] input_tile_10_address0;
output   input_tile_10_ce0;
output   input_tile_10_we0;
output  [15:0] input_tile_10_d0;
output  [4:0] input_tile_11_address0;
output   input_tile_11_ce0;
output   input_tile_11_we0;
output  [15:0] input_tile_11_d0;
output  [4:0] input_tile_12_address0;
output   input_tile_12_ce0;
output   input_tile_12_we0;
output  [15:0] input_tile_12_d0;
output  [4:0] input_tile_13_address0;
output   input_tile_13_ce0;
output   input_tile_13_we0;
output  [15:0] input_tile_13_d0;
output  [4:0] input_tile_14_address0;
output   input_tile_14_ce0;
output   input_tile_14_we0;
output  [15:0] input_tile_14_d0;
output  [4:0] input_tile_15_address0;
output   input_tile_15_ce0;
output   input_tile_15_we0;
output  [15:0] input_tile_15_d0;
output  [4:0] input_tile_16_address0;
output   input_tile_16_ce0;
output   input_tile_16_we0;
output  [15:0] input_tile_16_d0;
input  [8:0] zext_ln84;
input  [63:0] input_r;

reg ap_idle;
reg m_axi_gmem0_ARVALID;
reg m_axi_gmem0_RREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_idle_pp0;
reg   [0:0] icmp_ln84_reg_808;
reg   [0:0] icmp_ln84_reg_808_pp0_iter4_reg;
reg   [0:0] and_ln92_reg_868;
reg   [0:0] and_ln92_reg_868_pp0_iter4_reg;
reg    ap_predicate_op120_readreq_state6;
reg    ap_block_state6_io;
reg   [0:0] icmp_ln84_reg_808_pp0_iter12_reg;
reg   [0:0] and_ln92_reg_868_pp0_iter12_reg;
reg    ap_predicate_op143_read_state14;
reg    ap_block_state14_pp0_stage0_iter13;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln84_fu_354_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem0_blk_n_AR;
wire    ap_block_pp0_stage0;
reg    gmem0_blk_n_R;
reg    ap_block_pp0_stage0_11001;
wire   [9:0] zext_ln84_cast_fu_315_p1;
reg   [9:0] zext_ln84_cast_reg_798;
wire   [9:0] zext_ln73_cast_fu_319_p1;
reg   [9:0] zext_ln73_cast_reg_803;
reg   [0:0] icmp_ln84_reg_808_pp0_iter1_reg;
reg   [0:0] icmp_ln84_reg_808_pp0_iter2_reg;
reg   [0:0] icmp_ln84_reg_808_pp0_iter3_reg;
reg   [0:0] icmp_ln84_reg_808_pp0_iter5_reg;
reg   [0:0] icmp_ln84_reg_808_pp0_iter6_reg;
reg   [0:0] icmp_ln84_reg_808_pp0_iter7_reg;
reg   [0:0] icmp_ln84_reg_808_pp0_iter8_reg;
reg   [0:0] icmp_ln84_reg_808_pp0_iter9_reg;
reg   [0:0] icmp_ln84_reg_808_pp0_iter10_reg;
reg   [0:0] icmp_ln84_reg_808_pp0_iter11_reg;
reg   [0:0] icmp_ln84_reg_808_pp0_iter13_reg;
wire   [0:0] icmp_ln85_fu_375_p2;
reg   [0:0] icmp_ln85_reg_812;
wire   [1:0] select_ln84_3_fu_381_p3;
reg   [1:0] select_ln84_3_reg_819;
reg   [1:0] select_ln84_3_reg_819_pp0_iter1_reg;
reg   [1:0] select_ln84_3_reg_819_pp0_iter2_reg;
wire   [3:0] tx_mid2_fu_463_p3;
reg   [3:0] tx_mid2_reg_830;
wire   [3:0] select_ln85_fu_471_p3;
reg   [3:0] select_ln85_reg_837;
wire   [3:0] tmp1_fu_485_p2;
reg   [3:0] tmp1_reg_843;
reg   [2:0] tmp_reg_848;
reg   [2:0] tmp_56_reg_858;
wire   [9:0] add_ln89_fu_612_p2;
reg   [9:0] add_ln89_reg_863;
wire   [0:0] and_ln92_fu_623_p2;
reg   [0:0] and_ln92_reg_868_pp0_iter3_reg;
reg   [0:0] and_ln92_reg_868_pp0_iter5_reg;
reg   [0:0] and_ln92_reg_868_pp0_iter6_reg;
reg   [0:0] and_ln92_reg_868_pp0_iter7_reg;
reg   [0:0] and_ln92_reg_868_pp0_iter8_reg;
reg   [0:0] and_ln92_reg_868_pp0_iter9_reg;
reg   [0:0] and_ln92_reg_868_pp0_iter10_reg;
reg   [0:0] and_ln92_reg_868_pp0_iter11_reg;
reg   [0:0] and_ln92_reg_868_pp0_iter13_reg;
wire   [4:0] add_ln95_3_fu_679_p2;
reg   [4:0] add_ln95_3_reg_872;
reg   [4:0] add_ln95_3_reg_872_pp0_iter4_reg;
reg   [4:0] add_ln95_3_reg_872_pp0_iter5_reg;
reg   [4:0] add_ln95_3_reg_872_pp0_iter6_reg;
reg   [4:0] add_ln95_3_reg_872_pp0_iter7_reg;
reg   [4:0] add_ln95_3_reg_872_pp0_iter8_reg;
reg   [4:0] add_ln95_3_reg_872_pp0_iter9_reg;
reg   [4:0] add_ln95_3_reg_872_pp0_iter10_reg;
reg   [4:0] add_ln95_3_reg_872_pp0_iter11_reg;
reg   [4:0] add_ln95_3_reg_872_pp0_iter12_reg;
reg   [4:0] add_ln95_3_reg_872_pp0_iter13_reg;
(* use_dsp48 = "no" *) wire   [18:0] add_ln93_fu_688_p2;
reg   [18:0] add_ln93_reg_877;
reg   [63:0] gmem0_addr_reg_882;
wire   [1:0] trunc_ln85_fu_729_p1;
reg   [1:0] trunc_ln85_reg_888;
reg   [1:0] trunc_ln85_reg_888_pp0_iter9_reg;
reg   [1:0] trunc_ln85_reg_888_pp0_iter10_reg;
reg   [1:0] trunc_ln85_reg_888_pp0_iter11_reg;
reg   [1:0] trunc_ln85_reg_888_pp0_iter12_reg;
reg   [1:0] trunc_ln85_reg_888_pp0_iter13_reg;
wire   [1:0] trunc_ln86_fu_733_p1;
reg   [1:0] trunc_ln86_reg_892;
reg   [1:0] trunc_ln86_reg_892_pp0_iter9_reg;
reg   [1:0] trunc_ln86_reg_892_pp0_iter10_reg;
reg   [1:0] trunc_ln86_reg_892_pp0_iter11_reg;
reg   [1:0] trunc_ln86_reg_892_pp0_iter12_reg;
reg   [1:0] trunc_ln86_reg_892_pp0_iter13_reg;
reg   [15:0] v_reg_896;
reg   [15:0] ap_phi_mux_v_2_phi_fu_299_p4;
reg   [15:0] ap_phi_reg_pp0_iter14_v_2_reg_295;
wire   [15:0] ap_phi_reg_pp0_iter0_v_2_reg_295;
reg   [15:0] ap_phi_reg_pp0_iter1_v_2_reg_295;
reg   [15:0] ap_phi_reg_pp0_iter2_v_2_reg_295;
reg   [15:0] ap_phi_reg_pp0_iter3_v_2_reg_295;
reg   [15:0] ap_phi_reg_pp0_iter4_v_2_reg_295;
reg   [15:0] ap_phi_reg_pp0_iter5_v_2_reg_295;
reg   [15:0] ap_phi_reg_pp0_iter6_v_2_reg_295;
reg   [15:0] ap_phi_reg_pp0_iter7_v_2_reg_295;
reg   [15:0] ap_phi_reg_pp0_iter8_v_2_reg_295;
reg   [15:0] ap_phi_reg_pp0_iter9_v_2_reg_295;
reg   [15:0] ap_phi_reg_pp0_iter10_v_2_reg_295;
reg   [15:0] ap_phi_reg_pp0_iter11_v_2_reg_295;
reg   [15:0] ap_phi_reg_pp0_iter12_v_2_reg_295;
reg   [15:0] ap_phi_reg_pp0_iter13_v_2_reg_295;
wire   [63:0] zext_ln95_11_fu_737_p1;
wire  signed [63:0] sext_ln93_fu_719_p1;
reg   [3:0] tx_fu_128;
wire   [3:0] add_ln86_fu_497_p2;
wire    ap_loop_init;
reg   [3:0] ty_fu_132;
reg   [7:0] indvar_flatten_fu_136;
wire   [7:0] select_ln85_3_fu_399_p3;
reg   [7:0] ap_sig_allocacmp_indvar_flatten_load;
reg   [1:0] ic_fu_140;
reg   [1:0] ap_sig_allocacmp_ic_load;
reg   [7:0] indvar_flatten12_fu_144;
wire   [7:0] add_ln84_3_fu_360_p2;
reg   [7:0] ap_sig_allocacmp_indvar_flatten12_load;
reg    input_tile_12_we0_local;
reg    input_tile_12_ce0_local;
reg    input_tile_11_we0_local;
reg    input_tile_11_ce0_local;
reg    input_tile_13_we0_local;
reg    input_tile_13_ce0_local;
reg    input_tile_9_we0_local;
reg    input_tile_9_ce0_local;
reg    input_tile_we0_local;
reg    input_tile_ce0_local;
reg    input_tile_10_we0_local;
reg    input_tile_10_ce0_local;
reg    input_tile_15_we0_local;
reg    input_tile_15_ce0_local;
reg    input_tile_14_we0_local;
reg    input_tile_14_ce0_local;
reg    input_tile_16_we0_local;
reg    input_tile_16_ce0_local;
wire   [1:0] add_ln84_fu_369_p2;
wire   [7:0] add_ln85_3_fu_393_p2;
wire   [0:0] icmp_ln86_fu_440_p2;
wire   [0:0] xor_ln84_fu_435_p2;
wire   [3:0] select_ln84_fu_428_p3;
wire   [0:0] and_ln84_fu_446_p2;
wire   [0:0] empty_fu_458_p2;
wire   [3:0] add_ln85_fu_452_p2;
wire   [2:0] grp_fu_479_p1;
wire   [2:0] grp_fu_491_p1;
wire   [3:0] mul_ln85_fu_516_p0;
wire   [5:0] mul_ln85_fu_516_p1;
wire   [8:0] mul_ln85_fu_516_p2;
wire  signed [9:0] tmp1_cast_fu_532_p1;
wire   [9:0] empty_104_fu_535_p2;
wire   [0:0] tmp_53_fu_540_p3;
wire   [17:0] tmp_54_fu_554_p3;
wire   [15:0] tmp_55_fu_566_p3;
wire  signed [18:0] p_shl_fu_562_p1;
wire  signed [18:0] p_shl21_fu_574_p1;
wire   [3:0] mul_ln86_fu_587_p0;
wire   [5:0] mul_ln86_fu_587_p1;
wire   [8:0] mul_ln86_fu_587_p2;
wire   [3:0] add_ln89_2_fu_603_p2;
wire  signed [9:0] sext_ln89_fu_608_p1;
wire   [0:0] icmp_ln92_fu_617_p2;
wire   [0:0] rev_fu_548_p2;
wire   [3:0] p_shl3_fu_632_p3;
wire   [3:0] zext_ln95_fu_629_p1;
wire   [3:0] sub_ln95_fu_639_p2;
wire   [3:0] zext_ln85_2_fu_645_p1;
wire   [3:0] add_ln95_fu_648_p2;
wire   [2:0] trunc_ln95_fu_654_p1;
wire   [4:0] tmp_52_fu_658_p3;
wire   [4:0] zext_ln95_9_fu_666_p1;
wire   [4:0] sub_ln85_fu_670_p2;
wire   [4:0] zext_ln95_10_fu_676_p1;
wire   [18:0] add_ln93_fu_688_p0;
wire  signed [18:0] grp_fu_749_p3;
wire   [18:0] zext_ln93_fu_685_p1;
wire   [19:0] shl_ln_fu_693_p3;
wire   [63:0] zext_ln93_2_fu_700_p1;
wire   [63:0] add_ln93_2_fu_704_p2;
wire   [62:0] trunc_ln_fu_709_p4;
wire   [1:0] grp_fu_479_p2;
wire   [1:0] grp_fu_491_p2;
wire   [16:0] grp_fu_749_p0;
wire   [1:0] grp_fu_749_p1;
wire  signed [18:0] grp_fu_749_p2;
reg    grp_fu_479_ce;
reg    grp_fu_491_ce;
reg    grp_fu_749_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [18:0] grp_fu_749_p10;
wire   [8:0] mul_ln85_fu_516_p00;
wire   [8:0] mul_ln86_fu_587_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 tx_fu_128 = 4'd0;
#0 ty_fu_132 = 4'd0;
#0 indvar_flatten_fu_136 = 8'd0;
#0 ic_fu_140 = 2'd0;
#0 indvar_flatten12_fu_144 = 8'd0;
#0 ap_done_reg = 1'b0;
end

face_accelerate_urem_4ns_3ns_2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 2 ))
urem_4ns_3ns_2_8_1_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(select_ln85_fu_471_p3),
    .din1(grp_fu_479_p1),
    .ce(grp_fu_479_ce),
    .dout(grp_fu_479_p2)
);

face_accelerate_urem_4ns_3ns_2_8_1 #(
    .ID( 1 ),
    .NUM_STAGE( 8 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 2 ))
urem_4ns_3ns_2_8_1_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tx_mid2_fu_463_p3),
    .din1(grp_fu_491_p1),
    .ce(grp_fu_491_ce),
    .dout(grp_fu_491_p2)
);

face_accelerate_mul_4ns_6ns_9_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 9 ))
mul_4ns_6ns_9_1_1_U3(
    .din0(mul_ln85_fu_516_p0),
    .din1(mul_ln85_fu_516_p1),
    .dout(mul_ln85_fu_516_p2)
);

face_accelerate_mul_4ns_6ns_9_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 4 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 9 ))
mul_4ns_6ns_9_1_1_U4(
    .din0(mul_ln86_fu_587_p0),
    .din1(mul_ln86_fu_587_p1),
    .dout(mul_ln86_fu_587_p2)
);

face_accelerate_mac_muladd_17ns_2ns_19s_19_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 17 ),
    .din1_WIDTH( 2 ),
    .din2_WIDTH( 19 ),
    .dout_WIDTH( 19 ))
mac_muladd_17ns_2ns_19s_19_4_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_749_p0),
    .din1(grp_fu_749_p1),
    .din2(grp_fu_749_p2),
    .ce(grp_fu_749_ce),
    .dout(grp_fu_749_p3)
);

face_accelerate_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter13_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((icmp_ln84_reg_808_pp0_iter2_reg == 1'd0) & (1'd0 == and_ln92_reg_868))) begin
            ap_phi_reg_pp0_iter4_v_2_reg_295 <= 16'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter4_v_2_reg_295 <= ap_phi_reg_pp0_iter3_v_2_reg_295;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln84_fu_354_p2 == 1'd0))) begin
            ic_fu_140 <= select_ln84_3_fu_381_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            ic_fu_140 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln84_fu_354_p2 == 1'd0))) begin
            indvar_flatten12_fu_144 <= add_ln84_3_fu_360_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten12_fu_144 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln84_fu_354_p2 == 1'd0))) begin
            indvar_flatten_fu_136 <= select_ln85_3_fu_399_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_136 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            tx_fu_128 <= 4'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            tx_fu_128 <= add_ln86_fu_497_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            ty_fu_132 <= 4'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            ty_fu_132 <= select_ln85_fu_471_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln89_reg_863 <= add_ln89_fu_612_p2;
        add_ln93_reg_877 <= add_ln93_fu_688_p2;
        add_ln95_3_reg_872 <= add_ln95_3_fu_679_p2;
        add_ln95_3_reg_872_pp0_iter10_reg <= add_ln95_3_reg_872_pp0_iter9_reg;
        add_ln95_3_reg_872_pp0_iter11_reg <= add_ln95_3_reg_872_pp0_iter10_reg;
        add_ln95_3_reg_872_pp0_iter12_reg <= add_ln95_3_reg_872_pp0_iter11_reg;
        add_ln95_3_reg_872_pp0_iter13_reg <= add_ln95_3_reg_872_pp0_iter12_reg;
        add_ln95_3_reg_872_pp0_iter4_reg <= add_ln95_3_reg_872;
        add_ln95_3_reg_872_pp0_iter5_reg <= add_ln95_3_reg_872_pp0_iter4_reg;
        add_ln95_3_reg_872_pp0_iter6_reg <= add_ln95_3_reg_872_pp0_iter5_reg;
        add_ln95_3_reg_872_pp0_iter7_reg <= add_ln95_3_reg_872_pp0_iter6_reg;
        add_ln95_3_reg_872_pp0_iter8_reg <= add_ln95_3_reg_872_pp0_iter7_reg;
        add_ln95_3_reg_872_pp0_iter9_reg <= add_ln95_3_reg_872_pp0_iter8_reg;
        and_ln92_reg_868 <= and_ln92_fu_623_p2;
        and_ln92_reg_868_pp0_iter10_reg <= and_ln92_reg_868_pp0_iter9_reg;
        and_ln92_reg_868_pp0_iter11_reg <= and_ln92_reg_868_pp0_iter10_reg;
        and_ln92_reg_868_pp0_iter12_reg <= and_ln92_reg_868_pp0_iter11_reg;
        and_ln92_reg_868_pp0_iter13_reg <= and_ln92_reg_868_pp0_iter12_reg;
        and_ln92_reg_868_pp0_iter3_reg <= and_ln92_reg_868;
        and_ln92_reg_868_pp0_iter4_reg <= and_ln92_reg_868_pp0_iter3_reg;
        and_ln92_reg_868_pp0_iter5_reg <= and_ln92_reg_868_pp0_iter4_reg;
        and_ln92_reg_868_pp0_iter6_reg <= and_ln92_reg_868_pp0_iter5_reg;
        and_ln92_reg_868_pp0_iter7_reg <= and_ln92_reg_868_pp0_iter6_reg;
        and_ln92_reg_868_pp0_iter8_reg <= and_ln92_reg_868_pp0_iter7_reg;
        and_ln92_reg_868_pp0_iter9_reg <= and_ln92_reg_868_pp0_iter8_reg;
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        gmem0_addr_reg_882 <= sext_ln93_fu_719_p1;
        icmp_ln84_reg_808_pp0_iter10_reg <= icmp_ln84_reg_808_pp0_iter9_reg;
        icmp_ln84_reg_808_pp0_iter11_reg <= icmp_ln84_reg_808_pp0_iter10_reg;
        icmp_ln84_reg_808_pp0_iter12_reg <= icmp_ln84_reg_808_pp0_iter11_reg;
        icmp_ln84_reg_808_pp0_iter13_reg <= icmp_ln84_reg_808_pp0_iter12_reg;
        icmp_ln84_reg_808_pp0_iter2_reg <= icmp_ln84_reg_808_pp0_iter1_reg;
        icmp_ln84_reg_808_pp0_iter3_reg <= icmp_ln84_reg_808_pp0_iter2_reg;
        icmp_ln84_reg_808_pp0_iter4_reg <= icmp_ln84_reg_808_pp0_iter3_reg;
        icmp_ln84_reg_808_pp0_iter5_reg <= icmp_ln84_reg_808_pp0_iter4_reg;
        icmp_ln84_reg_808_pp0_iter6_reg <= icmp_ln84_reg_808_pp0_iter5_reg;
        icmp_ln84_reg_808_pp0_iter7_reg <= icmp_ln84_reg_808_pp0_iter6_reg;
        icmp_ln84_reg_808_pp0_iter8_reg <= icmp_ln84_reg_808_pp0_iter7_reg;
        icmp_ln84_reg_808_pp0_iter9_reg <= icmp_ln84_reg_808_pp0_iter8_reg;
        select_ln84_3_reg_819_pp0_iter2_reg <= select_ln84_3_reg_819_pp0_iter1_reg;
        tmp_56_reg_858 <= {{mul_ln86_fu_587_p2[8:6]}};
        tmp_reg_848 <= {{mul_ln85_fu_516_p2[8:6]}};
        trunc_ln85_reg_888 <= trunc_ln85_fu_729_p1;
        trunc_ln85_reg_888_pp0_iter10_reg <= trunc_ln85_reg_888_pp0_iter9_reg;
        trunc_ln85_reg_888_pp0_iter11_reg <= trunc_ln85_reg_888_pp0_iter10_reg;
        trunc_ln85_reg_888_pp0_iter12_reg <= trunc_ln85_reg_888_pp0_iter11_reg;
        trunc_ln85_reg_888_pp0_iter13_reg <= trunc_ln85_reg_888_pp0_iter12_reg;
        trunc_ln85_reg_888_pp0_iter9_reg <= trunc_ln85_reg_888;
        trunc_ln86_reg_892 <= trunc_ln86_fu_733_p1;
        trunc_ln86_reg_892_pp0_iter10_reg <= trunc_ln86_reg_892_pp0_iter9_reg;
        trunc_ln86_reg_892_pp0_iter11_reg <= trunc_ln86_reg_892_pp0_iter10_reg;
        trunc_ln86_reg_892_pp0_iter12_reg <= trunc_ln86_reg_892_pp0_iter11_reg;
        trunc_ln86_reg_892_pp0_iter13_reg <= trunc_ln86_reg_892_pp0_iter12_reg;
        trunc_ln86_reg_892_pp0_iter9_reg <= trunc_ln86_reg_892;
        v_reg_896 <= m_axi_gmem0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        icmp_ln84_reg_808 <= icmp_ln84_fu_354_p2;
        icmp_ln84_reg_808_pp0_iter1_reg <= icmp_ln84_reg_808;
        icmp_ln85_reg_812 <= icmp_ln85_fu_375_p2;
        select_ln84_3_reg_819 <= select_ln84_3_fu_381_p3;
        select_ln84_3_reg_819_pp0_iter1_reg <= select_ln84_3_reg_819;
        select_ln85_reg_837 <= select_ln85_fu_471_p3;
        tmp1_reg_843 <= tmp1_fu_485_p2;
        tx_mid2_reg_830 <= tx_mid2_fu_463_p3;
        zext_ln73_cast_reg_803[8 : 0] <= zext_ln73_cast_fu_319_p1[8 : 0];
        zext_ln84_cast_reg_798[8 : 0] <= zext_ln84_cast_fu_315_p1[8 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter10_v_2_reg_295 <= ap_phi_reg_pp0_iter9_v_2_reg_295;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter11_v_2_reg_295 <= ap_phi_reg_pp0_iter10_v_2_reg_295;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter11 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter12_v_2_reg_295 <= ap_phi_reg_pp0_iter11_v_2_reg_295;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter13_v_2_reg_295 <= ap_phi_reg_pp0_iter12_v_2_reg_295;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter14_v_2_reg_295 <= ap_phi_reg_pp0_iter13_v_2_reg_295;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter1_v_2_reg_295 <= ap_phi_reg_pp0_iter0_v_2_reg_295;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter2_v_2_reg_295 <= ap_phi_reg_pp0_iter1_v_2_reg_295;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter3_v_2_reg_295 <= ap_phi_reg_pp0_iter2_v_2_reg_295;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter5_v_2_reg_295 <= ap_phi_reg_pp0_iter4_v_2_reg_295;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter6_v_2_reg_295 <= ap_phi_reg_pp0_iter5_v_2_reg_295;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter7_v_2_reg_295 <= ap_phi_reg_pp0_iter6_v_2_reg_295;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter8_v_2_reg_295 <= ap_phi_reg_pp0_iter7_v_2_reg_295;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_phi_reg_pp0_iter9_v_2_reg_295 <= ap_phi_reg_pp0_iter8_v_2_reg_295;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln84_fu_354_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter13_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln84_reg_808_pp0_iter13_reg == 1'd0) & (1'd1 == and_ln92_reg_868_pp0_iter13_reg))) begin
        ap_phi_mux_v_2_phi_fu_299_p4 = v_reg_896;
    end else begin
        ap_phi_mux_v_2_phi_fu_299_p4 = ap_phi_reg_pp0_iter14_v_2_reg_295;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_ic_load = 2'd0;
    end else begin
        ap_sig_allocacmp_ic_load = ic_fu_140;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten12_load = 8'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten12_load = indvar_flatten12_fu_144;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 8'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_136;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (ap_predicate_op120_readreq_state6 == 1'b1))) begin
        gmem0_blk_n_AR = m_axi_gmem0_ARREADY;
    end else begin
        gmem0_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (ap_predicate_op143_read_state14 == 1'b1))) begin
        gmem0_blk_n_R = m_axi_gmem0_RVALID;
    end else begin
        gmem0_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_479_ce = 1'b1;
    end else begin
        grp_fu_479_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_491_ce = 1'b1;
    end else begin
        grp_fu_491_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_749_ce = 1'b1;
    end else begin
        grp_fu_749_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        input_tile_10_ce0_local = 1'b1;
    end else begin
        input_tile_10_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln86_reg_892_pp0_iter13_reg == 2'd0) & ~(trunc_ln86_reg_892_pp0_iter13_reg == 2'd1) & (ap_enable_reg_pp0_iter14 == 1'b1) & (trunc_ln85_reg_888_pp0_iter13_reg == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        input_tile_10_we0_local = 1'b1;
    end else begin
        input_tile_10_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        input_tile_11_ce0_local = 1'b1;
    end else begin
        input_tile_11_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (trunc_ln86_reg_892_pp0_iter13_reg == 2'd0) & (trunc_ln85_reg_888_pp0_iter13_reg == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        input_tile_11_we0_local = 1'b1;
    end else begin
        input_tile_11_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        input_tile_12_ce0_local = 1'b1;
    end else begin
        input_tile_12_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (trunc_ln86_reg_892_pp0_iter13_reg == 2'd1) & (trunc_ln85_reg_888_pp0_iter13_reg == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        input_tile_12_we0_local = 1'b1;
    end else begin
        input_tile_12_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        input_tile_13_ce0_local = 1'b1;
    end else begin
        input_tile_13_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln86_reg_892_pp0_iter13_reg == 2'd0) & ~(trunc_ln86_reg_892_pp0_iter13_reg == 2'd1) & (ap_enable_reg_pp0_iter14 == 1'b1) & (trunc_ln85_reg_888_pp0_iter13_reg == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        input_tile_13_we0_local = 1'b1;
    end else begin
        input_tile_13_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        input_tile_14_ce0_local = 1'b1;
    end else begin
        input_tile_14_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln85_reg_888_pp0_iter13_reg == 2'd0) & ~(trunc_ln85_reg_888_pp0_iter13_reg == 2'd1) & (ap_enable_reg_pp0_iter14 == 1'b1) & (trunc_ln86_reg_892_pp0_iter13_reg == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        input_tile_14_we0_local = 1'b1;
    end else begin
        input_tile_14_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        input_tile_15_ce0_local = 1'b1;
    end else begin
        input_tile_15_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln85_reg_888_pp0_iter13_reg == 2'd0) & ~(trunc_ln85_reg_888_pp0_iter13_reg == 2'd1) & (ap_enable_reg_pp0_iter14 == 1'b1) & (trunc_ln86_reg_892_pp0_iter13_reg == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        input_tile_15_we0_local = 1'b1;
    end else begin
        input_tile_15_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        input_tile_16_ce0_local = 1'b1;
    end else begin
        input_tile_16_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln85_reg_888_pp0_iter13_reg == 2'd0) & ~(trunc_ln86_reg_892_pp0_iter13_reg == 2'd0) & ~(trunc_ln86_reg_892_pp0_iter13_reg == 2'd1) & ~(trunc_ln85_reg_888_pp0_iter13_reg == 2'd1) & (ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        input_tile_16_we0_local = 1'b1;
    end else begin
        input_tile_16_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        input_tile_9_ce0_local = 1'b1;
    end else begin
        input_tile_9_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (trunc_ln86_reg_892_pp0_iter13_reg == 2'd1) & (trunc_ln85_reg_888_pp0_iter13_reg == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        input_tile_9_we0_local = 1'b1;
    end else begin
        input_tile_9_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        input_tile_ce0_local = 1'b1;
    end else begin
        input_tile_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (trunc_ln86_reg_892_pp0_iter13_reg == 2'd0) & (trunc_ln85_reg_888_pp0_iter13_reg == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        input_tile_we0_local = 1'b1;
    end else begin
        input_tile_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op120_readreq_state6 == 1'b1))) begin
        m_axi_gmem0_ARVALID = 1'b1;
    end else begin
        m_axi_gmem0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op143_read_state14 == 1'b1))) begin
        m_axi_gmem0_RREADY = 1'b1;
    end else begin
        m_axi_gmem0_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln84_3_fu_360_p2 = (ap_sig_allocacmp_indvar_flatten12_load + 8'd1);

assign add_ln84_fu_369_p2 = (ap_sig_allocacmp_ic_load + 2'd1);

assign add_ln85_3_fu_393_p2 = (ap_sig_allocacmp_indvar_flatten_load + 8'd1);

assign add_ln85_fu_452_p2 = (select_ln84_fu_428_p3 + 4'd1);

assign add_ln86_fu_497_p2 = (tx_mid2_fu_463_p3 + 4'd1);

assign add_ln89_2_fu_603_p2 = ($signed(tx_mid2_reg_830) + $signed(4'd15));

assign add_ln89_fu_612_p2 = ($signed(sext_ln89_fu_608_p1) + $signed(zext_ln84_cast_reg_798));

assign add_ln93_2_fu_704_p2 = (zext_ln93_2_fu_700_p1 + input_r);

assign add_ln93_fu_688_p0 = grp_fu_749_p3;

assign add_ln93_fu_688_p2 = (add_ln93_fu_688_p0 + zext_ln93_fu_685_p1);

assign add_ln95_3_fu_679_p2 = (sub_ln85_fu_670_p2 + zext_ln95_10_fu_676_p1);

assign add_ln95_fu_648_p2 = (sub_ln95_fu_639_p2 + zext_ln85_2_fu_645_p1);

assign and_ln84_fu_446_p2 = (xor_ln84_fu_435_p2 & icmp_ln86_fu_440_p2);

assign and_ln92_fu_623_p2 = (rev_fu_548_p2 & icmp_ln92_fu_617_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter13 == 1'b1) & (1'b1 == ap_block_state14_pp0_stage0_iter13)) | ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_block_state6_io)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter13 == 1'b1) & (1'b1 == ap_block_state14_pp0_stage0_iter13)) | ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_block_state6_io)));
end

always @ (*) begin
    ap_block_state14_pp0_stage0_iter13 = ((ap_predicate_op143_read_state14 == 1'b1) & (m_axi_gmem0_RVALID == 1'b0));
end

always @ (*) begin
    ap_block_state6_io = ((m_axi_gmem0_ARREADY == 1'b0) & (ap_predicate_op120_readreq_state6 == 1'b1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_phi_reg_pp0_iter0_v_2_reg_295 = 'bx;

always @ (*) begin
    ap_predicate_op120_readreq_state6 = ((1'd1 == and_ln92_reg_868_pp0_iter4_reg) & (icmp_ln84_reg_808_pp0_iter4_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op143_read_state14 = ((icmp_ln84_reg_808_pp0_iter12_reg == 1'd0) & (1'd1 == and_ln92_reg_868_pp0_iter12_reg));
end

assign ap_ready = ap_ready_sig;

assign empty_104_fu_535_p2 = ($signed(tmp1_cast_fu_532_p1) + $signed(zext_ln73_cast_reg_803));

assign empty_fu_458_p2 = (icmp_ln85_reg_812 | and_ln84_fu_446_p2);

assign grp_fu_479_p1 = 4'd3;

assign grp_fu_491_p1 = 4'd3;

assign grp_fu_749_p0 = 19'd102400;

assign grp_fu_749_p1 = grp_fu_749_p10;

assign grp_fu_749_p10 = select_ln84_3_fu_381_p3;

assign grp_fu_749_p2 = ($signed(p_shl_fu_562_p1) + $signed(p_shl21_fu_574_p1));

assign icmp_ln84_fu_354_p2 = ((ap_sig_allocacmp_indvar_flatten12_load == 8'd243) ? 1'b1 : 1'b0);

assign icmp_ln85_fu_375_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 8'd81) ? 1'b1 : 1'b0);

assign icmp_ln86_fu_440_p2 = ((tx_fu_128 == 4'd9) ? 1'b1 : 1'b0);

assign icmp_ln92_fu_617_p2 = ((add_ln89_fu_612_p2 < 10'd320) ? 1'b1 : 1'b0);

assign input_tile_10_address0 = zext_ln95_11_fu_737_p1;

assign input_tile_10_ce0 = input_tile_10_ce0_local;

assign input_tile_10_d0 = ap_phi_mux_v_2_phi_fu_299_p4;

assign input_tile_10_we0 = input_tile_10_we0_local;

assign input_tile_11_address0 = zext_ln95_11_fu_737_p1;

assign input_tile_11_ce0 = input_tile_11_ce0_local;

assign input_tile_11_d0 = ap_phi_mux_v_2_phi_fu_299_p4;

assign input_tile_11_we0 = input_tile_11_we0_local;

assign input_tile_12_address0 = zext_ln95_11_fu_737_p1;

assign input_tile_12_ce0 = input_tile_12_ce0_local;

assign input_tile_12_d0 = ap_phi_mux_v_2_phi_fu_299_p4;

assign input_tile_12_we0 = input_tile_12_we0_local;

assign input_tile_13_address0 = zext_ln95_11_fu_737_p1;

assign input_tile_13_ce0 = input_tile_13_ce0_local;

assign input_tile_13_d0 = ap_phi_mux_v_2_phi_fu_299_p4;

assign input_tile_13_we0 = input_tile_13_we0_local;

assign input_tile_14_address0 = zext_ln95_11_fu_737_p1;

assign input_tile_14_ce0 = input_tile_14_ce0_local;

assign input_tile_14_d0 = ap_phi_mux_v_2_phi_fu_299_p4;

assign input_tile_14_we0 = input_tile_14_we0_local;

assign input_tile_15_address0 = zext_ln95_11_fu_737_p1;

assign input_tile_15_ce0 = input_tile_15_ce0_local;

assign input_tile_15_d0 = ap_phi_mux_v_2_phi_fu_299_p4;

assign input_tile_15_we0 = input_tile_15_we0_local;

assign input_tile_16_address0 = zext_ln95_11_fu_737_p1;

assign input_tile_16_ce0 = input_tile_16_ce0_local;

assign input_tile_16_d0 = ap_phi_mux_v_2_phi_fu_299_p4;

assign input_tile_16_we0 = input_tile_16_we0_local;

assign input_tile_9_address0 = zext_ln95_11_fu_737_p1;

assign input_tile_9_ce0 = input_tile_9_ce0_local;

assign input_tile_9_d0 = ap_phi_mux_v_2_phi_fu_299_p4;

assign input_tile_9_we0 = input_tile_9_we0_local;

assign input_tile_address0 = zext_ln95_11_fu_737_p1;

assign input_tile_ce0 = input_tile_ce0_local;

assign input_tile_d0 = ap_phi_mux_v_2_phi_fu_299_p4;

assign input_tile_we0 = input_tile_we0_local;

assign m_axi_gmem0_ARADDR = gmem0_addr_reg_882;

assign m_axi_gmem0_ARBURST = 2'd0;

assign m_axi_gmem0_ARCACHE = 4'd0;

assign m_axi_gmem0_ARID = 1'd0;

assign m_axi_gmem0_ARLEN = 64'd1;

assign m_axi_gmem0_ARLOCK = 2'd0;

assign m_axi_gmem0_ARPROT = 3'd0;

assign m_axi_gmem0_ARQOS = 4'd0;

assign m_axi_gmem0_ARREGION = 4'd0;

assign m_axi_gmem0_ARSIZE = 3'd0;

assign m_axi_gmem0_ARUSER = 1'd0;

assign m_axi_gmem0_AWADDR = 64'd0;

assign m_axi_gmem0_AWBURST = 2'd0;

assign m_axi_gmem0_AWCACHE = 4'd0;

assign m_axi_gmem0_AWID = 1'd0;

assign m_axi_gmem0_AWLEN = 32'd0;

assign m_axi_gmem0_AWLOCK = 2'd0;

assign m_axi_gmem0_AWPROT = 3'd0;

assign m_axi_gmem0_AWQOS = 4'd0;

assign m_axi_gmem0_AWREGION = 4'd0;

assign m_axi_gmem0_AWSIZE = 3'd0;

assign m_axi_gmem0_AWUSER = 1'd0;

assign m_axi_gmem0_AWVALID = 1'b0;

assign m_axi_gmem0_BREADY = 1'b0;

assign m_axi_gmem0_WDATA = 16'd0;

assign m_axi_gmem0_WID = 1'd0;

assign m_axi_gmem0_WLAST = 1'b0;

assign m_axi_gmem0_WSTRB = 2'd0;

assign m_axi_gmem0_WUSER = 1'd0;

assign m_axi_gmem0_WVALID = 1'b0;

assign mul_ln85_fu_516_p0 = mul_ln85_fu_516_p00;

assign mul_ln85_fu_516_p00 = select_ln85_reg_837;

assign mul_ln85_fu_516_p1 = 9'd22;

assign mul_ln86_fu_587_p0 = mul_ln86_fu_587_p00;

assign mul_ln86_fu_587_p00 = tx_mid2_reg_830;

assign mul_ln86_fu_587_p1 = 9'd22;

assign p_shl21_fu_574_p1 = $signed(tmp_55_fu_566_p3);

assign p_shl3_fu_632_p3 = {{select_ln84_3_reg_819_pp0_iter2_reg}, {2'd0}};

assign p_shl_fu_562_p1 = $signed(tmp_54_fu_554_p3);

assign rev_fu_548_p2 = (tmp_53_fu_540_p3 ^ 1'd1);

assign select_ln84_3_fu_381_p3 = ((icmp_ln85_fu_375_p2[0:0] == 1'b1) ? add_ln84_fu_369_p2 : ap_sig_allocacmp_ic_load);

assign select_ln84_fu_428_p3 = ((icmp_ln85_reg_812[0:0] == 1'b1) ? 4'd0 : ty_fu_132);

assign select_ln85_3_fu_399_p3 = ((icmp_ln85_fu_375_p2[0:0] == 1'b1) ? 8'd1 : add_ln85_3_fu_393_p2);

assign select_ln85_fu_471_p3 = ((and_ln84_fu_446_p2[0:0] == 1'b1) ? add_ln85_fu_452_p2 : select_ln84_fu_428_p3);

assign sext_ln89_fu_608_p1 = $signed(add_ln89_2_fu_603_p2);

assign sext_ln93_fu_719_p1 = $signed(trunc_ln_fu_709_p4);

assign shl_ln_fu_693_p3 = {{add_ln93_reg_877}, {1'd0}};

assign sub_ln85_fu_670_p2 = (tmp_52_fu_658_p3 - zext_ln95_9_fu_666_p1);

assign sub_ln95_fu_639_p2 = (p_shl3_fu_632_p3 - zext_ln95_fu_629_p1);

assign tmp1_cast_fu_532_p1 = $signed(tmp1_reg_843);

assign tmp1_fu_485_p2 = ($signed(select_ln85_fu_471_p3) + $signed(4'd15));

assign tmp_52_fu_658_p3 = {{trunc_ln95_fu_654_p1}, {2'd0}};

assign tmp_53_fu_540_p3 = empty_104_fu_535_p2[32'd9];

assign tmp_54_fu_554_p3 = {{empty_104_fu_535_p2}, {8'd0}};

assign tmp_55_fu_566_p3 = {{empty_104_fu_535_p2}, {6'd0}};

assign trunc_ln85_fu_729_p1 = grp_fu_479_p2[1:0];

assign trunc_ln86_fu_733_p1 = grp_fu_491_p2[1:0];

assign trunc_ln95_fu_654_p1 = add_ln95_fu_648_p2[2:0];

assign trunc_ln_fu_709_p4 = {{add_ln93_2_fu_704_p2[63:1]}};

assign tx_mid2_fu_463_p3 = ((empty_fu_458_p2[0:0] == 1'b1) ? 4'd0 : tx_fu_128);

assign xor_ln84_fu_435_p2 = (icmp_ln85_reg_812 ^ 1'd1);

assign zext_ln73_cast_fu_319_p1 = zext_ln73;

assign zext_ln84_cast_fu_315_p1 = zext_ln84;

assign zext_ln85_2_fu_645_p1 = tmp_reg_848;

assign zext_ln93_2_fu_700_p1 = shl_ln_fu_693_p3;

assign zext_ln93_fu_685_p1 = add_ln89_reg_863;

assign zext_ln95_10_fu_676_p1 = tmp_56_reg_858;

assign zext_ln95_11_fu_737_p1 = add_ln95_3_reg_872_pp0_iter13_reg;

assign zext_ln95_9_fu_666_p1 = add_ln95_fu_648_p2;

assign zext_ln95_fu_629_p1 = select_ln84_3_reg_819_pp0_iter2_reg;

always @ (posedge ap_clk) begin
    zext_ln84_cast_reg_798[9] <= 1'b0;
    zext_ln73_cast_reg_803[9] <= 1'b0;
end

endmodule //face_accelerate_conv2d_layer_Pipeline_LOAD_TILE_VITIS_LOOP_85_3_VITIS_LOOP_86_4_2
