// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module face_accelerate_conv2d_layer_Pipeline_LOAD_TILE_VITIS_LOOP_85_3_VITIS_LOOP_86_4 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY,
        m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY,
        m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST,
        m_axi_gmem0_WID,
        m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST,
        m_axi_gmem0_RID,
        m_axi_gmem0_RFIFONUM,
        m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID,
        m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP,
        m_axi_gmem0_BID,
        m_axi_gmem0_BUSER,
        input_tile_address0,
        input_tile_ce0,
        input_tile_we0,
        input_tile_d0,
        add_ln79,
        input_r
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem0_AWVALID;
input   m_axi_gmem0_AWREADY;
output  [63:0] m_axi_gmem0_AWADDR;
output  [0:0] m_axi_gmem0_AWID;
output  [31:0] m_axi_gmem0_AWLEN;
output  [2:0] m_axi_gmem0_AWSIZE;
output  [1:0] m_axi_gmem0_AWBURST;
output  [1:0] m_axi_gmem0_AWLOCK;
output  [3:0] m_axi_gmem0_AWCACHE;
output  [2:0] m_axi_gmem0_AWPROT;
output  [3:0] m_axi_gmem0_AWQOS;
output  [3:0] m_axi_gmem0_AWREGION;
output  [0:0] m_axi_gmem0_AWUSER;
output   m_axi_gmem0_WVALID;
input   m_axi_gmem0_WREADY;
output  [15:0] m_axi_gmem0_WDATA;
output  [1:0] m_axi_gmem0_WSTRB;
output   m_axi_gmem0_WLAST;
output  [0:0] m_axi_gmem0_WID;
output  [0:0] m_axi_gmem0_WUSER;
output   m_axi_gmem0_ARVALID;
input   m_axi_gmem0_ARREADY;
output  [63:0] m_axi_gmem0_ARADDR;
output  [0:0] m_axi_gmem0_ARID;
output  [31:0] m_axi_gmem0_ARLEN;
output  [2:0] m_axi_gmem0_ARSIZE;
output  [1:0] m_axi_gmem0_ARBURST;
output  [1:0] m_axi_gmem0_ARLOCK;
output  [3:0] m_axi_gmem0_ARCACHE;
output  [2:0] m_axi_gmem0_ARPROT;
output  [3:0] m_axi_gmem0_ARQOS;
output  [3:0] m_axi_gmem0_ARREGION;
output  [0:0] m_axi_gmem0_ARUSER;
input   m_axi_gmem0_RVALID;
output   m_axi_gmem0_RREADY;
input  [15:0] m_axi_gmem0_RDATA;
input   m_axi_gmem0_RLAST;
input  [0:0] m_axi_gmem0_RID;
input  [9:0] m_axi_gmem0_RFIFONUM;
input  [0:0] m_axi_gmem0_RUSER;
input  [1:0] m_axi_gmem0_RRESP;
input   m_axi_gmem0_BVALID;
output   m_axi_gmem0_BREADY;
input  [1:0] m_axi_gmem0_BRESP;
input  [0:0] m_axi_gmem0_BID;
input  [0:0] m_axi_gmem0_BUSER;
output  [9:0] input_tile_address0;
output   input_tile_ce0;
output   input_tile_we0;
output  [15:0] input_tile_d0;
input  [10:0] add_ln79;
input  [63:0] input_r;

reg ap_idle;
reg m_axi_gmem0_ARVALID;
reg m_axi_gmem0_RREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_idle_pp0;
reg   [0:0] first_iter_0_reg_528;
reg   [0:0] first_iter_0_reg_528_pp0_iter3_reg;
reg    ap_block_state5_io;
reg    ap_block_state13_pp0_stage0_iter12;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln84_fu_180_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem0_blk_n_R;
wire    ap_block_pp0_stage0;
reg    gmem0_blk_n_AR;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] icmp_ln85_fu_201_p2;
reg   [0:0] icmp_ln85_reg_499;
wire   [5:0] select_ln84_1_fu_207_p3;
reg   [5:0] select_ln84_1_reg_506;
reg   [5:0] select_ln84_1_reg_506_pp0_iter1_reg;
wire   [2:0] tx_mid2_fu_289_p3;
reg   [2:0] tx_mid2_reg_516;
wire   [2:0] select_ln85_fu_297_p3;
reg   [2:0] select_ln85_reg_521;
wire   [0:0] first_iter_0_fu_305_p2;
reg   [0:0] first_iter_0_reg_528_pp0_iter2_reg;
wire   [9:0] add_ln95_1_fu_395_p2;
reg   [9:0] add_ln95_1_reg_537;
reg   [9:0] add_ln95_1_reg_537_pp0_iter3_reg;
reg   [9:0] add_ln95_1_reg_537_pp0_iter4_reg;
reg   [9:0] add_ln95_1_reg_537_pp0_iter5_reg;
reg   [9:0] add_ln95_1_reg_537_pp0_iter6_reg;
reg   [9:0] add_ln95_1_reg_537_pp0_iter7_reg;
reg   [9:0] add_ln95_1_reg_537_pp0_iter8_reg;
reg   [9:0] add_ln95_1_reg_537_pp0_iter9_reg;
reg   [9:0] add_ln95_1_reg_537_pp0_iter10_reg;
reg   [9:0] add_ln95_1_reg_537_pp0_iter11_reg;
reg   [9:0] add_ln95_1_reg_537_pp0_iter12_reg;
reg   [63:0] gmem0_addr_reg_542;
reg   [15:0] v_reg_548;
wire   [63:0] zext_ln95_15_fu_437_p1;
wire  signed [63:0] sext_ln86_fu_427_p1;
reg   [2:0] tx_fu_92;
wire   [2:0] add_ln86_fu_311_p2;
wire    ap_loop_init;
reg   [2:0] ty_fu_96;
reg   [5:0] indvar_flatten_fu_100;
wire   [5:0] select_ln85_1_fu_225_p3;
reg   [5:0] ap_sig_allocacmp_indvar_flatten_load;
reg   [5:0] ic_fu_104;
reg   [5:0] ap_sig_allocacmp_ic_load;
reg   [9:0] indvar_flatten12_fu_108;
wire   [9:0] add_ln84_1_fu_186_p2;
reg   [9:0] ap_sig_allocacmp_indvar_flatten12_load;
reg    input_tile_we0_local;
reg    input_tile_ce0_local;
wire   [5:0] add_ln84_fu_195_p2;
wire   [5:0] add_ln85_4_fu_219_p2;
wire   [0:0] icmp_ln86_fu_266_p2;
wire   [0:0] xor_ln84_fu_261_p2;
wire   [2:0] select_ln84_fu_254_p3;
wire   [0:0] and_ln84_fu_272_p2;
wire   [0:0] empty_113_fu_284_p2;
wire   [2:0] add_ln85_2_fu_278_p2;
wire   [7:0] tmp_fu_327_p3;
wire   [5:0] tmp_62_fu_338_p3;
wire   [8:0] zext_ln85_fu_334_p1;
wire   [8:0] zext_ln85_5_fu_345_p1;
wire   [8:0] add_ln85_5_fu_349_p2;
wire   [10:0] zext_ln85_2_fu_355_p1;
wire   [10:0] add_ln85_3_fu_359_p2;
wire   [7:0] tmp_4_fu_368_p3;
wire   [7:0] zext_ln95_fu_375_p1;
wire   [7:0] add_ln95_fu_378_p2;
wire   [9:0] tmp_63_fu_384_p3;
wire   [9:0] zext_ln95_14_fu_392_p1;
wire   [16:0] grp_fu_441_p3;
wire   [17:0] shl_ln_fu_401_p3;
wire   [63:0] zext_ln85_4_fu_408_p1;
wire   [63:0] add_ln85_1_fu_412_p2;
wire   [62:0] trunc_ln_fu_417_p4;
wire   [10:0] grp_fu_441_p0;
wire   [5:0] grp_fu_441_p1;
wire   [10:0] grp_fu_441_p2;
reg    grp_fu_441_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [16:0] grp_fu_441_p10;
wire   [16:0] grp_fu_441_p20;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 tx_fu_92 = 3'd0;
#0 ty_fu_96 = 3'd0;
#0 indvar_flatten_fu_100 = 6'd0;
#0 ic_fu_104 = 6'd0;
#0 indvar_flatten12_fu_108 = 10'd0;
#0 ap_done_reg = 1'b0;
end

face_accelerate_mac_muladd_11ns_6ns_11ns_17_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 11 ),
    .dout_WIDTH( 17 ))
mac_muladd_11ns_6ns_11ns_17_4_1_U632(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_441_p0),
    .din1(grp_fu_441_p1),
    .din2(grp_fu_441_p2),
    .ce(grp_fu_441_ce),
    .dout(grp_fu_441_p3)
);

face_accelerate_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter12_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln84_fu_180_p2 == 1'd0))) begin
            ic_fu_104 <= select_ln84_1_fu_207_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            ic_fu_104 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln84_fu_180_p2 == 1'd0))) begin
            indvar_flatten12_fu_108 <= add_ln84_1_fu_186_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten12_fu_108 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln84_fu_180_p2 == 1'd0))) begin
            indvar_flatten_fu_100 <= select_ln85_1_fu_225_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_100 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            tx_fu_92 <= 3'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            tx_fu_92 <= add_ln86_fu_311_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            ty_fu_96 <= 3'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            ty_fu_96 <= select_ln85_fu_297_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln95_1_reg_537 <= add_ln95_1_fu_395_p2;
        add_ln95_1_reg_537_pp0_iter10_reg <= add_ln95_1_reg_537_pp0_iter9_reg;
        add_ln95_1_reg_537_pp0_iter11_reg <= add_ln95_1_reg_537_pp0_iter10_reg;
        add_ln95_1_reg_537_pp0_iter12_reg <= add_ln95_1_reg_537_pp0_iter11_reg;
        add_ln95_1_reg_537_pp0_iter3_reg <= add_ln95_1_reg_537;
        add_ln95_1_reg_537_pp0_iter4_reg <= add_ln95_1_reg_537_pp0_iter3_reg;
        add_ln95_1_reg_537_pp0_iter5_reg <= add_ln95_1_reg_537_pp0_iter4_reg;
        add_ln95_1_reg_537_pp0_iter6_reg <= add_ln95_1_reg_537_pp0_iter5_reg;
        add_ln95_1_reg_537_pp0_iter7_reg <= add_ln95_1_reg_537_pp0_iter6_reg;
        add_ln95_1_reg_537_pp0_iter8_reg <= add_ln95_1_reg_537_pp0_iter7_reg;
        add_ln95_1_reg_537_pp0_iter9_reg <= add_ln95_1_reg_537_pp0_iter8_reg;
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        first_iter_0_reg_528_pp0_iter2_reg <= first_iter_0_reg_528;
        first_iter_0_reg_528_pp0_iter3_reg <= first_iter_0_reg_528_pp0_iter2_reg;
        gmem0_addr_reg_542 <= sext_ln86_fu_427_p1;
        v_reg_548 <= m_axi_gmem0_RDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        first_iter_0_reg_528 <= first_iter_0_fu_305_p2;
        icmp_ln85_reg_499 <= icmp_ln85_fu_201_p2;
        select_ln84_1_reg_506 <= select_ln84_1_fu_207_p3;
        select_ln84_1_reg_506_pp0_iter1_reg <= select_ln84_1_reg_506;
        select_ln85_reg_521 <= select_ln85_fu_297_p3;
        tx_mid2_reg_516 <= tx_mid2_fu_289_p3;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln84_fu_180_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter12_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_ic_load = 6'd0;
    end else begin
        ap_sig_allocacmp_ic_load = ic_fu_104;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten12_load = 10'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten12_load = indvar_flatten12_fu_108;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 6'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_100;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (first_iter_0_reg_528_pp0_iter3_reg == 1'd1))) begin
        gmem0_blk_n_AR = m_axi_gmem0_ARREADY;
    end else begin
        gmem0_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        gmem0_blk_n_R = m_axi_gmem0_RVALID;
    end else begin
        gmem0_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_441_ce = 1'b1;
    end else begin
        grp_fu_441_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        input_tile_ce0_local = 1'b1;
    end else begin
        input_tile_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        input_tile_we0_local = 1'b1;
    end else begin
        input_tile_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (first_iter_0_reg_528_pp0_iter3_reg == 1'd1))) begin
        m_axi_gmem0_ARVALID = 1'b1;
    end else begin
        m_axi_gmem0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmem0_RREADY = 1'b1;
    end else begin
        m_axi_gmem0_RREADY = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln84_1_fu_186_p2 = (ap_sig_allocacmp_indvar_flatten12_load + 10'd1);

assign add_ln84_fu_195_p2 = (ap_sig_allocacmp_ic_load + 6'd1);

assign add_ln85_1_fu_412_p2 = (zext_ln85_4_fu_408_p1 + input_r);

assign add_ln85_2_fu_278_p2 = (select_ln84_fu_254_p3 + 3'd1);

assign add_ln85_3_fu_359_p2 = (add_ln79 + zext_ln85_2_fu_355_p1);

assign add_ln85_4_fu_219_p2 = (ap_sig_allocacmp_indvar_flatten_load + 6'd1);

assign add_ln85_5_fu_349_p2 = (zext_ln85_fu_334_p1 + zext_ln85_5_fu_345_p1);

assign add_ln86_fu_311_p2 = (tx_mid2_fu_289_p3 + 3'd1);

assign add_ln95_1_fu_395_p2 = (tmp_63_fu_384_p3 + zext_ln95_14_fu_392_p1);

assign add_ln95_fu_378_p2 = (tmp_4_fu_368_p3 + zext_ln95_fu_375_p1);

assign and_ln84_fu_272_p2 = (xor_ln84_fu_261_p2 & icmp_ln86_fu_266_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b1 == ap_block_state13_pp0_stage0_iter12)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_io)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter12 == 1'b1) & (1'b1 == ap_block_state13_pp0_stage0_iter12)) | ((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_block_state5_io)));
end

always @ (*) begin
    ap_block_state13_pp0_stage0_iter12 = (m_axi_gmem0_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state5_io = ((m_axi_gmem0_ARREADY == 1'b0) & (first_iter_0_reg_528_pp0_iter3_reg == 1'd1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign empty_113_fu_284_p2 = (icmp_ln85_reg_499 | and_ln84_fu_272_p2);

assign first_iter_0_fu_305_p2 = ((tx_mid2_fu_289_p3 == 3'd0) ? 1'b1 : 1'b0);

assign grp_fu_441_p0 = 17'd1600;

assign grp_fu_441_p1 = grp_fu_441_p10;

assign grp_fu_441_p10 = select_ln84_1_fu_207_p3;

assign grp_fu_441_p2 = grp_fu_441_p20;

assign grp_fu_441_p20 = add_ln85_3_fu_359_p2;

assign icmp_ln84_fu_180_p2 = ((ap_sig_allocacmp_indvar_flatten12_load == 10'd768) ? 1'b1 : 1'b0);

assign icmp_ln85_fu_201_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 6'd16) ? 1'b1 : 1'b0);

assign icmp_ln86_fu_266_p2 = ((tx_fu_92 == 3'd4) ? 1'b1 : 1'b0);

assign input_tile_address0 = zext_ln95_15_fu_437_p1;

assign input_tile_ce0 = input_tile_ce0_local;

assign input_tile_d0 = v_reg_548;

assign input_tile_we0 = input_tile_we0_local;

assign m_axi_gmem0_ARADDR = gmem0_addr_reg_542;

assign m_axi_gmem0_ARBURST = 2'd0;

assign m_axi_gmem0_ARCACHE = 4'd0;

assign m_axi_gmem0_ARID = 1'd0;

assign m_axi_gmem0_ARLEN = 64'd4;

assign m_axi_gmem0_ARLOCK = 2'd0;

assign m_axi_gmem0_ARPROT = 3'd0;

assign m_axi_gmem0_ARQOS = 4'd0;

assign m_axi_gmem0_ARREGION = 4'd0;

assign m_axi_gmem0_ARSIZE = 3'd0;

assign m_axi_gmem0_ARUSER = 1'd0;

assign m_axi_gmem0_AWADDR = 64'd0;

assign m_axi_gmem0_AWBURST = 2'd0;

assign m_axi_gmem0_AWCACHE = 4'd0;

assign m_axi_gmem0_AWID = 1'd0;

assign m_axi_gmem0_AWLEN = 32'd0;

assign m_axi_gmem0_AWLOCK = 2'd0;

assign m_axi_gmem0_AWPROT = 3'd0;

assign m_axi_gmem0_AWQOS = 4'd0;

assign m_axi_gmem0_AWREGION = 4'd0;

assign m_axi_gmem0_AWSIZE = 3'd0;

assign m_axi_gmem0_AWUSER = 1'd0;

assign m_axi_gmem0_AWVALID = 1'b0;

assign m_axi_gmem0_BREADY = 1'b0;

assign m_axi_gmem0_WDATA = 16'd0;

assign m_axi_gmem0_WID = 1'd0;

assign m_axi_gmem0_WLAST = 1'b0;

assign m_axi_gmem0_WSTRB = 2'd0;

assign m_axi_gmem0_WUSER = 1'd0;

assign m_axi_gmem0_WVALID = 1'b0;

assign select_ln84_1_fu_207_p3 = ((icmp_ln85_fu_201_p2[0:0] == 1'b1) ? add_ln84_fu_195_p2 : ap_sig_allocacmp_ic_load);

assign select_ln84_fu_254_p3 = ((icmp_ln85_reg_499[0:0] == 1'b1) ? 3'd0 : ty_fu_96);

assign select_ln85_1_fu_225_p3 = ((icmp_ln85_fu_201_p2[0:0] == 1'b1) ? 6'd1 : add_ln85_4_fu_219_p2);

assign select_ln85_fu_297_p3 = ((and_ln84_fu_272_p2[0:0] == 1'b1) ? add_ln85_2_fu_278_p2 : select_ln84_fu_254_p3);

assign sext_ln86_fu_427_p1 = $signed(trunc_ln_fu_417_p4);

assign shl_ln_fu_401_p3 = {{grp_fu_441_p3}, {1'd0}};

assign tmp_4_fu_368_p3 = {{select_ln84_1_reg_506_pp0_iter1_reg}, {2'd0}};

assign tmp_62_fu_338_p3 = {{select_ln85_reg_521}, {3'd0}};

assign tmp_63_fu_384_p3 = {{add_ln95_fu_378_p2}, {2'd0}};

assign tmp_fu_327_p3 = {{select_ln85_reg_521}, {5'd0}};

assign trunc_ln_fu_417_p4 = {{add_ln85_1_fu_412_p2[63:1]}};

assign tx_mid2_fu_289_p3 = ((empty_113_fu_284_p2[0:0] == 1'b1) ? 3'd0 : tx_fu_92);

assign xor_ln84_fu_261_p2 = (icmp_ln85_reg_499 ^ 1'd1);

assign zext_ln85_2_fu_355_p1 = add_ln85_5_fu_349_p2;

assign zext_ln85_4_fu_408_p1 = shl_ln_fu_401_p3;

assign zext_ln85_5_fu_345_p1 = tmp_62_fu_338_p3;

assign zext_ln85_fu_334_p1 = tmp_fu_327_p3;

assign zext_ln95_14_fu_392_p1 = tx_mid2_reg_516;

assign zext_ln95_15_fu_437_p1 = add_ln95_1_reg_537_pp0_iter12_reg;

assign zext_ln95_fu_375_p1 = select_ln85_reg_521;

endmodule //face_accelerate_conv2d_layer_Pipeline_LOAD_TILE_VITIS_LOOP_85_3_VITIS_LOOP_86_4
