// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module face_accelerate_conv2d_layer_Pipeline_WRITE_TILE_VITIS_LOOP_200_12 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY,
        m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY,
        m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST,
        m_axi_gmem0_WID,
        m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST,
        m_axi_gmem0_RID,
        m_axi_gmem0_RFIFONUM,
        m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID,
        m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP,
        m_axi_gmem0_BID,
        m_axi_gmem0_BUSER,
        empty_53,
        empty_54,
        empty_55,
        empty_56,
        empty_57,
        empty_58,
        empty_59,
        empty_60,
        empty_61,
        empty_62,
        empty_63,
        empty_64,
        empty_65,
        empty_66,
        empty_67,
        empty,
        add_ln79,
        phi_mul,
        output_r
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem0_AWVALID;
input   m_axi_gmem0_AWREADY;
output  [63:0] m_axi_gmem0_AWADDR;
output  [0:0] m_axi_gmem0_AWID;
output  [31:0] m_axi_gmem0_AWLEN;
output  [2:0] m_axi_gmem0_AWSIZE;
output  [1:0] m_axi_gmem0_AWBURST;
output  [1:0] m_axi_gmem0_AWLOCK;
output  [3:0] m_axi_gmem0_AWCACHE;
output  [2:0] m_axi_gmem0_AWPROT;
output  [3:0] m_axi_gmem0_AWQOS;
output  [3:0] m_axi_gmem0_AWREGION;
output  [0:0] m_axi_gmem0_AWUSER;
output   m_axi_gmem0_WVALID;
input   m_axi_gmem0_WREADY;
output  [15:0] m_axi_gmem0_WDATA;
output  [1:0] m_axi_gmem0_WSTRB;
output   m_axi_gmem0_WLAST;
output  [0:0] m_axi_gmem0_WID;
output  [0:0] m_axi_gmem0_WUSER;
output   m_axi_gmem0_ARVALID;
input   m_axi_gmem0_ARREADY;
output  [63:0] m_axi_gmem0_ARADDR;
output  [0:0] m_axi_gmem0_ARID;
output  [31:0] m_axi_gmem0_ARLEN;
output  [2:0] m_axi_gmem0_ARSIZE;
output  [1:0] m_axi_gmem0_ARBURST;
output  [1:0] m_axi_gmem0_ARLOCK;
output  [3:0] m_axi_gmem0_ARCACHE;
output  [2:0] m_axi_gmem0_ARPROT;
output  [3:0] m_axi_gmem0_ARQOS;
output  [3:0] m_axi_gmem0_ARREGION;
output  [0:0] m_axi_gmem0_ARUSER;
input   m_axi_gmem0_RVALID;
output   m_axi_gmem0_RREADY;
input  [15:0] m_axi_gmem0_RDATA;
input   m_axi_gmem0_RLAST;
input  [0:0] m_axi_gmem0_RID;
input  [9:0] m_axi_gmem0_RFIFONUM;
input  [0:0] m_axi_gmem0_RUSER;
input  [1:0] m_axi_gmem0_RRESP;
input   m_axi_gmem0_BVALID;
output   m_axi_gmem0_BREADY;
input  [1:0] m_axi_gmem0_BRESP;
input  [0:0] m_axi_gmem0_BID;
input  [0:0] m_axi_gmem0_BUSER;
input  [21:0] empty_53;
input  [21:0] empty_54;
input  [21:0] empty_55;
input  [21:0] empty_56;
input  [21:0] empty_57;
input  [21:0] empty_58;
input  [21:0] empty_59;
input  [21:0] empty_60;
input  [21:0] empty_61;
input  [21:0] empty_62;
input  [21:0] empty_63;
input  [21:0] empty_64;
input  [21:0] empty_65;
input  [21:0] empty_66;
input  [21:0] empty_67;
input  [21:0] empty;
input  [10:0] add_ln79;
input  [13:0] phi_mul;
input  [63:0] output_r;

reg ap_idle;
reg m_axi_gmem0_AWVALID;
reg m_axi_gmem0_WVALID;
reg m_axi_gmem0_BREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_idle_pp0;
reg   [0:0] first_iter_3_reg_693;
reg   [0:0] first_iter_3_reg_693_pp0_iter2_reg;
reg    ap_block_state4_io;
reg   [0:0] icmp_ln200_1_reg_707;
reg   [0:0] icmp_ln200_1_reg_707_pp0_iter8_reg;
reg    ap_block_state10_pp0_stage0_iter9;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln199_fu_288_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem0_blk_n_B;
wire    ap_block_pp0_stage0;
reg    gmem0_blk_n_W;
reg    gmem0_blk_n_AW;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] first_iter_3_fu_339_p2;
wire   [8:0] empty_91_fu_369_p2;
reg   [8:0] empty_91_reg_697;
reg   [15:0] trunc_ln7_reg_702;
reg   [15:0] trunc_ln7_reg_702_pp0_iter2_reg;
reg   [15:0] trunc_ln7_reg_702_pp0_iter3_reg;
wire   [0:0] icmp_ln200_1_fu_503_p2;
reg   [0:0] icmp_ln200_1_reg_707_pp0_iter2_reg;
reg   [0:0] icmp_ln200_1_reg_707_pp0_iter3_reg;
reg   [0:0] icmp_ln200_1_reg_707_pp0_iter4_reg;
reg   [0:0] icmp_ln200_1_reg_707_pp0_iter5_reg;
reg   [0:0] icmp_ln200_1_reg_707_pp0_iter6_reg;
reg   [0:0] icmp_ln200_1_reg_707_pp0_iter7_reg;
reg   [63:0] gmem0_addr_reg_711;
wire  signed [63:0] sext_ln200_fu_563_p1;
reg    ap_block_pp0_stage0_01001;
reg   [2:0] tj_fu_128;
wire   [2:0] add_ln200_fu_497_p2;
wire    ap_loop_init;
reg   [2:0] ti_fu_132;
wire   [2:0] select_ln199_1_fu_331_p3;
reg   [4:0] indvar_flatten26_fu_136;
wire   [4:0] add_ln199_1_fu_294_p2;
reg   [4:0] ap_sig_allocacmp_indvar_flatten26_load;
wire   [0:0] icmp_ln200_fu_317_p2;
wire   [2:0] add_ln199_fu_311_p2;
wire   [2:0] select_ln199_fu_323_p3;
wire   [7:0] tmp_40_fu_345_p3;
wire   [5:0] tmp_41_fu_357_p3;
wire   [8:0] p_shl_fu_353_p1;
wire   [8:0] p_shl10_fu_365_p1;
wire   [21:0] tmp_fu_383_p9;
wire   [1:0] trunc_ln200_fu_379_p1;
wire   [21:0] tmp_1_fu_403_p9;
wire   [21:0] tmp_2_fu_423_p9;
wire   [21:0] tmp_3_fu_443_p9;
wire   [21:0] tmp_fu_383_p11;
wire   [21:0] tmp_1_fu_403_p11;
wire   [21:0] tmp_2_fu_423_p11;
wire   [21:0] tmp_3_fu_443_p11;
wire   [21:0] value_fu_463_p9;
wire   [1:0] value_fu_463_p10;
wire   [21:0] value_fu_463_p11;
wire   [10:0] p_cast6_fu_519_p1;
wire   [10:0] tmp2_fu_522_p2;
wire   [13:0] tmp2_cast_fu_527_p1;
wire   [13:0] empty_92_fu_531_p2;
wire   [14:0] tmp_s_fu_536_p3;
wire   [63:0] p_cast12_fu_544_p1;
wire   [63:0] empty_93_fu_548_p2;
wire   [62:0] trunc_ln5_fu_553_p4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [1:0] tmp_fu_383_p1;
wire   [1:0] tmp_fu_383_p3;
wire  signed [1:0] tmp_fu_383_p5;
wire  signed [1:0] tmp_fu_383_p7;
wire   [1:0] tmp_1_fu_403_p1;
wire   [1:0] tmp_1_fu_403_p3;
wire  signed [1:0] tmp_1_fu_403_p5;
wire  signed [1:0] tmp_1_fu_403_p7;
wire   [1:0] tmp_2_fu_423_p1;
wire   [1:0] tmp_2_fu_423_p3;
wire  signed [1:0] tmp_2_fu_423_p5;
wire  signed [1:0] tmp_2_fu_423_p7;
wire   [1:0] tmp_3_fu_443_p1;
wire   [1:0] tmp_3_fu_443_p3;
wire  signed [1:0] tmp_3_fu_443_p5;
wire  signed [1:0] tmp_3_fu_443_p7;
wire   [1:0] value_fu_463_p1;
wire   [1:0] value_fu_463_p3;
wire  signed [1:0] value_fu_463_p5;
wire  signed [1:0] value_fu_463_p7;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 tj_fu_128 = 3'd0;
#0 ti_fu_132 = 3'd0;
#0 indvar_flatten26_fu_136 = 5'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) face_accelerate_sparsemux_9_2_22_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 22 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 22 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 22 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 22 ),
    .def_WIDTH( 22 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 22 ))
sparsemux_9_2_22_1_1_U706(
    .din0(empty_53),
    .din1(empty_54),
    .din2(empty_55),
    .din3(empty_56),
    .def(tmp_fu_383_p9),
    .sel(trunc_ln200_fu_379_p1),
    .dout(tmp_fu_383_p11)
);

(* dissolve_hierarchy = "yes" *) face_accelerate_sparsemux_9_2_22_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 22 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 22 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 22 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 22 ),
    .def_WIDTH( 22 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 22 ))
sparsemux_9_2_22_1_1_U707(
    .din0(empty_57),
    .din1(empty_58),
    .din2(empty_59),
    .din3(empty_60),
    .def(tmp_1_fu_403_p9),
    .sel(trunc_ln200_fu_379_p1),
    .dout(tmp_1_fu_403_p11)
);

(* dissolve_hierarchy = "yes" *) face_accelerate_sparsemux_9_2_22_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 22 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 22 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 22 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 22 ),
    .def_WIDTH( 22 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 22 ))
sparsemux_9_2_22_1_1_U708(
    .din0(empty_61),
    .din1(empty_62),
    .din2(empty_63),
    .din3(empty_64),
    .def(tmp_2_fu_423_p9),
    .sel(trunc_ln200_fu_379_p1),
    .dout(tmp_2_fu_423_p11)
);

(* dissolve_hierarchy = "yes" *) face_accelerate_sparsemux_9_2_22_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 22 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 22 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 22 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 22 ),
    .def_WIDTH( 22 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 22 ))
sparsemux_9_2_22_1_1_U709(
    .din0(empty_65),
    .din1(empty_66),
    .din2(empty_67),
    .din3(empty),
    .def(tmp_3_fu_443_p9),
    .sel(trunc_ln200_fu_379_p1),
    .dout(tmp_3_fu_443_p11)
);

(* dissolve_hierarchy = "yes" *) face_accelerate_sparsemux_9_2_22_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h0 ),
    .din0_WIDTH( 22 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 22 ),
    .CASE2( 2'h2 ),
    .din2_WIDTH( 22 ),
    .CASE3( 2'h3 ),
    .din3_WIDTH( 22 ),
    .def_WIDTH( 22 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 22 ))
sparsemux_9_2_22_1_1_U710(
    .din0(tmp_fu_383_p11),
    .din1(tmp_1_fu_403_p11),
    .din2(tmp_2_fu_423_p11),
    .din3(tmp_3_fu_443_p11),
    .def(value_fu_463_p9),
    .sel(value_fu_463_p10),
    .dout(value_fu_463_p11)
);

face_accelerate_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter8_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln199_fu_288_p2 == 1'd0))) begin
            indvar_flatten26_fu_136 <= add_ln199_1_fu_294_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten26_fu_136 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            ti_fu_132 <= 3'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            ti_fu_132 <= select_ln199_1_fu_331_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if ((ap_loop_init == 1'b1)) begin
            tj_fu_128 <= 3'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            tj_fu_128 <= add_ln200_fu_497_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        empty_91_reg_697[8 : 3] <= empty_91_fu_369_p2[8 : 3];
        first_iter_3_reg_693 <= first_iter_3_fu_339_p2;
        icmp_ln200_1_reg_707 <= icmp_ln200_1_fu_503_p2;
        trunc_ln7_reg_702 <= {{value_fu_463_p11[21:6]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        first_iter_3_reg_693_pp0_iter2_reg <= first_iter_3_reg_693;
        gmem0_addr_reg_711 <= sext_ln200_fu_563_p1;
        icmp_ln200_1_reg_707_pp0_iter2_reg <= icmp_ln200_1_reg_707;
        icmp_ln200_1_reg_707_pp0_iter3_reg <= icmp_ln200_1_reg_707_pp0_iter2_reg;
        icmp_ln200_1_reg_707_pp0_iter4_reg <= icmp_ln200_1_reg_707_pp0_iter3_reg;
        icmp_ln200_1_reg_707_pp0_iter5_reg <= icmp_ln200_1_reg_707_pp0_iter4_reg;
        icmp_ln200_1_reg_707_pp0_iter6_reg <= icmp_ln200_1_reg_707_pp0_iter5_reg;
        icmp_ln200_1_reg_707_pp0_iter7_reg <= icmp_ln200_1_reg_707_pp0_iter6_reg;
        icmp_ln200_1_reg_707_pp0_iter8_reg <= icmp_ln200_1_reg_707_pp0_iter7_reg;
        trunc_ln7_reg_702_pp0_iter2_reg <= trunc_ln7_reg_702;
        trunc_ln7_reg_702_pp0_iter3_reg <= trunc_ln7_reg_702_pp0_iter2_reg;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln199_fu_288_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter8_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten26_load = 5'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten26_load = indvar_flatten26_fu_136;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (first_iter_3_reg_693_pp0_iter2_reg == 1'd1))) begin
        gmem0_blk_n_AW = m_axi_gmem0_AWREADY;
    end else begin
        gmem0_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (icmp_ln200_1_reg_707_pp0_iter8_reg == 1'd1))) begin
        gmem0_blk_n_B = m_axi_gmem0_BVALID;
    end else begin
        gmem0_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        gmem0_blk_n_W = m_axi_gmem0_WREADY;
    end else begin
        gmem0_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (first_iter_3_reg_693_pp0_iter2_reg == 1'd1))) begin
        m_axi_gmem0_AWVALID = 1'b1;
    end else begin
        m_axi_gmem0_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln200_1_reg_707_pp0_iter8_reg == 1'd1))) begin
        m_axi_gmem0_BREADY = 1'b1;
    end else begin
        m_axi_gmem0_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmem0_WVALID = 1'b1;
    end else begin
        m_axi_gmem0_WVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln199_1_fu_294_p2 = (ap_sig_allocacmp_indvar_flatten26_load + 5'd1);

assign add_ln199_fu_311_p2 = (ti_fu_132 + 3'd1);

assign add_ln200_fu_497_p2 = (select_ln199_fu_323_p3 + 3'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_block_state10_pp0_stage0_iter9));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_block_state10_pp0_stage0_iter9)) | ((m_axi_gmem0_WREADY == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_io)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_block_state10_pp0_stage0_iter9)) | ((m_axi_gmem0_WREADY == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state4_io)));
end

always @ (*) begin
    ap_block_state10_pp0_stage0_iter9 = ((icmp_ln200_1_reg_707_pp0_iter8_reg == 1'd1) & (m_axi_gmem0_BVALID == 1'b0));
end

always @ (*) begin
    ap_block_state4_io = ((m_axi_gmem0_AWREADY == 1'b0) & (first_iter_3_reg_693_pp0_iter2_reg == 1'd1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign empty_91_fu_369_p2 = (p_shl_fu_353_p1 + p_shl10_fu_365_p1);

assign empty_92_fu_531_p2 = (tmp2_cast_fu_527_p1 + phi_mul);

assign empty_93_fu_548_p2 = (p_cast12_fu_544_p1 + output_r);

assign first_iter_3_fu_339_p2 = ((select_ln199_fu_323_p3 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln199_fu_288_p2 = ((ap_sig_allocacmp_indvar_flatten26_load == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln200_1_fu_503_p2 = ((add_ln200_fu_497_p2 == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln200_fu_317_p2 = ((tj_fu_128 == 3'd4) ? 1'b1 : 1'b0);

assign m_axi_gmem0_ARADDR = 64'd0;

assign m_axi_gmem0_ARBURST = 2'd0;

assign m_axi_gmem0_ARCACHE = 4'd0;

assign m_axi_gmem0_ARID = 1'd0;

assign m_axi_gmem0_ARLEN = 32'd0;

assign m_axi_gmem0_ARLOCK = 2'd0;

assign m_axi_gmem0_ARPROT = 3'd0;

assign m_axi_gmem0_ARQOS = 4'd0;

assign m_axi_gmem0_ARREGION = 4'd0;

assign m_axi_gmem0_ARSIZE = 3'd0;

assign m_axi_gmem0_ARUSER = 1'd0;

assign m_axi_gmem0_ARVALID = 1'b0;

assign m_axi_gmem0_AWADDR = gmem0_addr_reg_711;

assign m_axi_gmem0_AWBURST = 2'd0;

assign m_axi_gmem0_AWCACHE = 4'd0;

assign m_axi_gmem0_AWID = 1'd0;

assign m_axi_gmem0_AWLEN = 64'd4;

assign m_axi_gmem0_AWLOCK = 2'd0;

assign m_axi_gmem0_AWPROT = 3'd0;

assign m_axi_gmem0_AWQOS = 4'd0;

assign m_axi_gmem0_AWREGION = 4'd0;

assign m_axi_gmem0_AWSIZE = 3'd0;

assign m_axi_gmem0_AWUSER = 1'd0;

assign m_axi_gmem0_RREADY = 1'b0;

assign m_axi_gmem0_WDATA = trunc_ln7_reg_702_pp0_iter3_reg;

assign m_axi_gmem0_WID = 1'd0;

assign m_axi_gmem0_WLAST = 1'b0;

assign m_axi_gmem0_WSTRB = 2'd3;

assign m_axi_gmem0_WUSER = 1'd0;

assign p_cast12_fu_544_p1 = tmp_s_fu_536_p3;

assign p_cast6_fu_519_p1 = empty_91_reg_697;

assign p_shl10_fu_365_p1 = tmp_41_fu_357_p3;

assign p_shl_fu_353_p1 = tmp_40_fu_345_p3;

assign select_ln199_1_fu_331_p3 = ((icmp_ln200_fu_317_p2[0:0] == 1'b1) ? add_ln199_fu_311_p2 : ti_fu_132);

assign select_ln199_fu_323_p3 = ((icmp_ln200_fu_317_p2[0:0] == 1'b1) ? 3'd0 : tj_fu_128);

assign sext_ln200_fu_563_p1 = $signed(trunc_ln5_fu_553_p4);

assign tmp2_cast_fu_527_p1 = tmp2_fu_522_p2;

assign tmp2_fu_522_p2 = (add_ln79 + p_cast6_fu_519_p1);

assign tmp_1_fu_403_p9 = 'bx;

assign tmp_2_fu_423_p9 = 'bx;

assign tmp_3_fu_443_p9 = 'bx;

assign tmp_40_fu_345_p3 = {{select_ln199_1_fu_331_p3}, {5'd0}};

assign tmp_41_fu_357_p3 = {{select_ln199_1_fu_331_p3}, {3'd0}};

assign tmp_fu_383_p9 = 'bx;

assign tmp_s_fu_536_p3 = {{empty_92_fu_531_p2}, {1'd0}};

assign trunc_ln200_fu_379_p1 = select_ln199_fu_323_p3[1:0];

assign trunc_ln5_fu_553_p4 = {{empty_93_fu_548_p2[63:1]}};

assign value_fu_463_p10 = select_ln199_1_fu_331_p3[1:0];

assign value_fu_463_p9 = 'bx;

always @ (posedge ap_clk) begin
    empty_91_reg_697[2:0] <= 3'b000;
end

endmodule //face_accelerate_conv2d_layer_Pipeline_WRITE_TILE_VITIS_LOOP_200_12
