// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module face_accelerate_conv2d_layer_48_48_40_40_3_1_1_true_Pipeline_INIT_TILE_VITIS_LOOP_110_6 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        sext_ln109,
        out_tile_78_out,
        out_tile_78_out_ap_vld,
        out_tile_77_out,
        out_tile_77_out_ap_vld,
        out_tile_76_out,
        out_tile_76_out_ap_vld,
        out_tile_75_out,
        out_tile_75_out_ap_vld,
        out_tile_74_out,
        out_tile_74_out_ap_vld,
        out_tile_73_out,
        out_tile_73_out_ap_vld,
        out_tile_72_out,
        out_tile_72_out_ap_vld,
        out_tile_71_out,
        out_tile_71_out_ap_vld,
        out_tile_70_out,
        out_tile_70_out_ap_vld,
        out_tile_69_out,
        out_tile_69_out_ap_vld,
        out_tile_68_out,
        out_tile_68_out_ap_vld,
        out_tile_67_out,
        out_tile_67_out_ap_vld,
        out_tile_66_out,
        out_tile_66_out_ap_vld,
        out_tile_65_out,
        out_tile_65_out_ap_vld,
        out_tile_64_out,
        out_tile_64_out_ap_vld,
        out_tile_63_out,
        out_tile_63_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [21:0] sext_ln109;
output  [31:0] out_tile_78_out;
output   out_tile_78_out_ap_vld;
output  [31:0] out_tile_77_out;
output   out_tile_77_out_ap_vld;
output  [31:0] out_tile_76_out;
output   out_tile_76_out_ap_vld;
output  [31:0] out_tile_75_out;
output   out_tile_75_out_ap_vld;
output  [31:0] out_tile_74_out;
output   out_tile_74_out_ap_vld;
output  [31:0] out_tile_73_out;
output   out_tile_73_out_ap_vld;
output  [31:0] out_tile_72_out;
output   out_tile_72_out_ap_vld;
output  [31:0] out_tile_71_out;
output   out_tile_71_out_ap_vld;
output  [31:0] out_tile_70_out;
output   out_tile_70_out_ap_vld;
output  [31:0] out_tile_69_out;
output   out_tile_69_out_ap_vld;
output  [31:0] out_tile_68_out;
output   out_tile_68_out_ap_vld;
output  [31:0] out_tile_67_out;
output   out_tile_67_out_ap_vld;
output  [31:0] out_tile_66_out;
output   out_tile_66_out_ap_vld;
output  [31:0] out_tile_65_out;
output   out_tile_65_out_ap_vld;
output  [31:0] out_tile_64_out;
output   out_tile_64_out_ap_vld;
output  [31:0] out_tile_63_out;
output   out_tile_63_out_ap_vld;

reg ap_idle;
reg[31:0] out_tile_78_out;
reg out_tile_78_out_ap_vld;
reg[31:0] out_tile_77_out;
reg out_tile_77_out_ap_vld;
reg[31:0] out_tile_76_out;
reg out_tile_76_out_ap_vld;
reg[31:0] out_tile_75_out;
reg out_tile_75_out_ap_vld;
reg[31:0] out_tile_74_out;
reg out_tile_74_out_ap_vld;
reg[31:0] out_tile_73_out;
reg out_tile_73_out_ap_vld;
reg[31:0] out_tile_72_out;
reg out_tile_72_out_ap_vld;
reg[31:0] out_tile_71_out;
reg out_tile_71_out_ap_vld;
reg[31:0] out_tile_70_out;
reg out_tile_70_out_ap_vld;
reg[31:0] out_tile_69_out;
reg out_tile_69_out_ap_vld;
reg[31:0] out_tile_68_out;
reg out_tile_68_out_ap_vld;
reg[31:0] out_tile_67_out;
reg out_tile_67_out_ap_vld;
reg[31:0] out_tile_66_out;
reg out_tile_66_out_ap_vld;
reg[31:0] out_tile_65_out;
reg out_tile_65_out_ap_vld;
reg[31:0] out_tile_64_out;
reg out_tile_64_out_ap_vld;
reg[31:0] out_tile_63_out;
reg out_tile_63_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln109_fu_208_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire  signed [31:0] sext_ln109_cast_fu_90_p1;
reg  signed [31:0] sext_ln109_cast_reg_384;
wire    ap_block_pp0_stage0_11001;
wire    ap_block_pp0_stage0;
wire   [1:0] trunc_ln109_fu_259_p1;
wire   [1:0] trunc_ln110_fu_263_p1;
wire    ap_loop_init;
reg   [2:0] tj_fu_72;
wire   [2:0] add_ln110_fu_347_p2;
reg   [2:0] ti_fu_76;
wire   [2:0] select_ln109_2_fu_251_p3;
reg   [4:0] indvar_flatten19_fu_80;
wire   [4:0] add_ln109_2_fu_214_p2;
reg   [4:0] ap_sig_allocacmp_indvar_flatten19_load;
wire   [0:0] icmp_ln110_fu_237_p2;
wire   [2:0] add_ln109_fu_231_p2;
wire   [2:0] select_ln109_fu_243_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
reg    ap_condition_268;
reg    ap_condition_271;
reg    ap_condition_274;
reg    ap_condition_277;
reg    ap_condition_280;
reg    ap_condition_283;
reg    ap_condition_286;
reg    ap_condition_289;
reg    ap_condition_292;
reg    ap_condition_295;
reg    ap_condition_298;
reg    ap_condition_301;
reg    ap_condition_304;
reg    ap_condition_307;
reg    ap_condition_310;
reg    ap_condition_313;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 tj_fu_72 = 3'd0;
#0 ti_fu_76 = 3'd0;
#0 indvar_flatten19_fu_80 = 5'd0;
#0 ap_done_reg = 1'b0;
end

face_accelerate_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln109_fu_208_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten19_fu_80 <= add_ln109_2_fu_214_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten19_fu_80 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            ti_fu_76 <= 3'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            ti_fu_76 <= select_ln109_2_fu_251_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            tj_fu_72 <= 3'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            tj_fu_72 <= add_ln110_fu_347_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sext_ln109_cast_reg_384 <= sext_ln109_cast_fu_90_p1;
    end
end

always @ (*) begin
    if (((icmp_ln109_fu_208_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten19_load = 5'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten19_load = indvar_flatten19_fu_80;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            out_tile_63_out = 'bx;
        end else if ((1'b1 == ap_condition_268)) begin
            out_tile_63_out = sext_ln109_cast_reg_384;
        end else begin
            out_tile_63_out = 'bx;
        end
    end else begin
        out_tile_63_out = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln110_fu_263_p1 == 2'd2) & (trunc_ln109_fu_259_p1 == 2'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        out_tile_63_out_ap_vld = 1'b1;
    end else begin
        out_tile_63_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            out_tile_64_out = 'bx;
        end else if ((1'b1 == ap_condition_271)) begin
            out_tile_64_out = sext_ln109_cast_reg_384;
        end else begin
            out_tile_64_out = 'bx;
        end
    end else begin
        out_tile_64_out = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln110_fu_263_p1 == 2'd1) & (trunc_ln109_fu_259_p1 == 2'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        out_tile_64_out_ap_vld = 1'b1;
    end else begin
        out_tile_64_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            out_tile_65_out = 'bx;
        end else if ((1'b1 == ap_condition_274)) begin
            out_tile_65_out = sext_ln109_cast_reg_384;
        end else begin
            out_tile_65_out = 'bx;
        end
    end else begin
        out_tile_65_out = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln110_fu_263_p1 == 2'd0) & (trunc_ln109_fu_259_p1 == 2'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        out_tile_65_out_ap_vld = 1'b1;
    end else begin
        out_tile_65_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            out_tile_66_out = 'bx;
        end else if ((1'b1 == ap_condition_277)) begin
            out_tile_66_out = sext_ln109_cast_reg_384;
        end else begin
            out_tile_66_out = 'bx;
        end
    end else begin
        out_tile_66_out = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln110_fu_263_p1 == 2'd3) & (trunc_ln109_fu_259_p1 == 2'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        out_tile_66_out_ap_vld = 1'b1;
    end else begin
        out_tile_66_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            out_tile_67_out = 'bx;
        end else if ((1'b1 == ap_condition_280)) begin
            out_tile_67_out = sext_ln109_cast_reg_384;
        end else begin
            out_tile_67_out = 'bx;
        end
    end else begin
        out_tile_67_out = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln110_fu_263_p1 == 2'd2) & (trunc_ln109_fu_259_p1 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        out_tile_67_out_ap_vld = 1'b1;
    end else begin
        out_tile_67_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            out_tile_68_out = 'bx;
        end else if ((1'b1 == ap_condition_283)) begin
            out_tile_68_out = sext_ln109_cast_reg_384;
        end else begin
            out_tile_68_out = 'bx;
        end
    end else begin
        out_tile_68_out = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln110_fu_263_p1 == 2'd1) & (trunc_ln109_fu_259_p1 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        out_tile_68_out_ap_vld = 1'b1;
    end else begin
        out_tile_68_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            out_tile_69_out = 'bx;
        end else if ((1'b1 == ap_condition_286)) begin
            out_tile_69_out = sext_ln109_cast_reg_384;
        end else begin
            out_tile_69_out = 'bx;
        end
    end else begin
        out_tile_69_out = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln110_fu_263_p1 == 2'd0) & (trunc_ln109_fu_259_p1 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        out_tile_69_out_ap_vld = 1'b1;
    end else begin
        out_tile_69_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            out_tile_70_out = 'bx;
        end else if ((1'b1 == ap_condition_289)) begin
            out_tile_70_out = sext_ln109_cast_reg_384;
        end else begin
            out_tile_70_out = 'bx;
        end
    end else begin
        out_tile_70_out = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln110_fu_263_p1 == 2'd3) & (trunc_ln109_fu_259_p1 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        out_tile_70_out_ap_vld = 1'b1;
    end else begin
        out_tile_70_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            out_tile_71_out = 'bx;
        end else if ((1'b1 == ap_condition_292)) begin
            out_tile_71_out = sext_ln109_cast_reg_384;
        end else begin
            out_tile_71_out = 'bx;
        end
    end else begin
        out_tile_71_out = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln110_fu_263_p1 == 2'd2) & (trunc_ln109_fu_259_p1 == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        out_tile_71_out_ap_vld = 1'b1;
    end else begin
        out_tile_71_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            out_tile_72_out = 'bx;
        end else if ((1'b1 == ap_condition_295)) begin
            out_tile_72_out = sext_ln109_cast_reg_384;
        end else begin
            out_tile_72_out = 'bx;
        end
    end else begin
        out_tile_72_out = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln110_fu_263_p1 == 2'd1) & (trunc_ln109_fu_259_p1 == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        out_tile_72_out_ap_vld = 1'b1;
    end else begin
        out_tile_72_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            out_tile_73_out = 'bx;
        end else if ((1'b1 == ap_condition_298)) begin
            out_tile_73_out = sext_ln109_cast_reg_384;
        end else begin
            out_tile_73_out = 'bx;
        end
    end else begin
        out_tile_73_out = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln110_fu_263_p1 == 2'd0) & (trunc_ln109_fu_259_p1 == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        out_tile_73_out_ap_vld = 1'b1;
    end else begin
        out_tile_73_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            out_tile_74_out = 'bx;
        end else if ((1'b1 == ap_condition_301)) begin
            out_tile_74_out = sext_ln109_cast_reg_384;
        end else begin
            out_tile_74_out = 'bx;
        end
    end else begin
        out_tile_74_out = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln110_fu_263_p1 == 2'd3) & (trunc_ln109_fu_259_p1 == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        out_tile_74_out_ap_vld = 1'b1;
    end else begin
        out_tile_74_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            out_tile_75_out = 'bx;
        end else if ((1'b1 == ap_condition_304)) begin
            out_tile_75_out = sext_ln109_cast_reg_384;
        end else begin
            out_tile_75_out = 'bx;
        end
    end else begin
        out_tile_75_out = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln110_fu_263_p1 == 2'd2) & (trunc_ln109_fu_259_p1 == 2'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        out_tile_75_out_ap_vld = 1'b1;
    end else begin
        out_tile_75_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            out_tile_76_out = 'bx;
        end else if ((1'b1 == ap_condition_307)) begin
            out_tile_76_out = sext_ln109_cast_reg_384;
        end else begin
            out_tile_76_out = 'bx;
        end
    end else begin
        out_tile_76_out = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln110_fu_263_p1 == 2'd1) & (trunc_ln109_fu_259_p1 == 2'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        out_tile_76_out_ap_vld = 1'b1;
    end else begin
        out_tile_76_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            out_tile_77_out = 'bx;
        end else if ((1'b1 == ap_condition_310)) begin
            out_tile_77_out = sext_ln109_cast_reg_384;
        end else begin
            out_tile_77_out = 'bx;
        end
    end else begin
        out_tile_77_out = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln110_fu_263_p1 == 2'd0) & (trunc_ln109_fu_259_p1 == 2'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        out_tile_77_out_ap_vld = 1'b1;
    end else begin
        out_tile_77_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            out_tile_78_out = 'bx;
        end else if ((1'b1 == ap_condition_313)) begin
            out_tile_78_out = sext_ln109_cast_reg_384;
        end else begin
            out_tile_78_out = 'bx;
        end
    end else begin
        out_tile_78_out = 'bx;
    end
end

always @ (*) begin
    if ((((trunc_ln110_fu_263_p1 == 2'd3) & (trunc_ln109_fu_259_p1 == 2'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        out_tile_78_out_ap_vld = 1'b1;
    end else begin
        out_tile_78_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln109_2_fu_214_p2 = (ap_sig_allocacmp_indvar_flatten19_load + 5'd1);

assign add_ln109_fu_231_p2 = (ti_fu_76 + 3'd1);

assign add_ln110_fu_347_p2 = (select_ln109_fu_243_p3 + 3'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_268 = ((trunc_ln110_fu_263_p1 == 2'd2) & (trunc_ln109_fu_259_p1 == 2'd2) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_271 = ((trunc_ln110_fu_263_p1 == 2'd1) & (trunc_ln109_fu_259_p1 == 2'd2) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_274 = ((trunc_ln110_fu_263_p1 == 2'd0) & (trunc_ln109_fu_259_p1 == 2'd2) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_277 = ((trunc_ln110_fu_263_p1 == 2'd3) & (trunc_ln109_fu_259_p1 == 2'd2) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_280 = ((trunc_ln110_fu_263_p1 == 2'd2) & (trunc_ln109_fu_259_p1 == 2'd1) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_283 = ((trunc_ln110_fu_263_p1 == 2'd1) & (trunc_ln109_fu_259_p1 == 2'd1) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_286 = ((trunc_ln110_fu_263_p1 == 2'd0) & (trunc_ln109_fu_259_p1 == 2'd1) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_289 = ((trunc_ln110_fu_263_p1 == 2'd3) & (trunc_ln109_fu_259_p1 == 2'd1) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_292 = ((trunc_ln110_fu_263_p1 == 2'd2) & (trunc_ln109_fu_259_p1 == 2'd0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_295 = ((trunc_ln110_fu_263_p1 == 2'd1) & (trunc_ln109_fu_259_p1 == 2'd0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_298 = ((trunc_ln110_fu_263_p1 == 2'd0) & (trunc_ln109_fu_259_p1 == 2'd0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_301 = ((trunc_ln110_fu_263_p1 == 2'd3) & (trunc_ln109_fu_259_p1 == 2'd0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_304 = ((trunc_ln110_fu_263_p1 == 2'd2) & (trunc_ln109_fu_259_p1 == 2'd3) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_307 = ((trunc_ln110_fu_263_p1 == 2'd1) & (trunc_ln109_fu_259_p1 == 2'd3) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_310 = ((trunc_ln110_fu_263_p1 == 2'd0) & (trunc_ln109_fu_259_p1 == 2'd3) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_condition_313 = ((trunc_ln110_fu_263_p1 == 2'd3) & (trunc_ln109_fu_259_p1 == 2'd3) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign icmp_ln109_fu_208_p2 = ((ap_sig_allocacmp_indvar_flatten19_load == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln110_fu_237_p2 = ((tj_fu_72 == 3'd4) ? 1'b1 : 1'b0);

assign select_ln109_2_fu_251_p3 = ((icmp_ln110_fu_237_p2[0:0] == 1'b1) ? add_ln109_fu_231_p2 : ti_fu_76);

assign select_ln109_fu_243_p3 = ((icmp_ln110_fu_237_p2[0:0] == 1'b1) ? 3'd0 : tj_fu_72);

assign sext_ln109_cast_fu_90_p1 = $signed(sext_ln109);

assign trunc_ln109_fu_259_p1 = select_ln109_2_fu_251_p3[1:0];

assign trunc_ln110_fu_263_p1 = select_ln109_fu_243_p3[1:0];

endmodule //face_accelerate_conv2d_layer_48_48_40_40_3_1_1_true_Pipeline_INIT_TILE_VITIS_LOOP_110_6
