-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity face_accelerate_conv2d_layer_48_6_40_40_1_1_0_false_Pipeline_INIT_TILE_VITIS_LOOP_110_6 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    sext_ln109 : IN STD_LOGIC_VECTOR (21 downto 0);
    shl_i_i_i112167_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    shl_i_i_i112167_out_ap_vld : OUT STD_LOGIC;
    shl_i_i_i112164_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    shl_i_i_i112164_out_ap_vld : OUT STD_LOGIC;
    shl_i_i_i112161_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    shl_i_i_i112161_out_ap_vld : OUT STD_LOGIC;
    shl_i_i_i112158_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    shl_i_i_i112158_out_ap_vld : OUT STD_LOGIC;
    shl_i_i_i112153_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    shl_i_i_i112153_out_ap_vld : OUT STD_LOGIC;
    shl_i_i_i112150_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    shl_i_i_i112150_out_ap_vld : OUT STD_LOGIC;
    shl_i_i_i112147_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    shl_i_i_i112147_out_ap_vld : OUT STD_LOGIC;
    shl_i_i_i112144_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    shl_i_i_i112144_out_ap_vld : OUT STD_LOGIC;
    shl_i_i_i112143_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    shl_i_i_i112143_out_ap_vld : OUT STD_LOGIC;
    shl_i_i_i112140_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    shl_i_i_i112140_out_ap_vld : OUT STD_LOGIC;
    shl_i_i_i112137_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    shl_i_i_i112137_out_ap_vld : OUT STD_LOGIC;
    shl_i_i_i112134_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    shl_i_i_i112134_out_ap_vld : OUT STD_LOGIC;
    shl_i_i_i112131_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    shl_i_i_i112131_out_ap_vld : OUT STD_LOGIC;
    shl_i_i_i112128_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    shl_i_i_i112128_out_ap_vld : OUT STD_LOGIC;
    shl_i_i_i112125_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    shl_i_i_i112125_out_ap_vld : OUT STD_LOGIC;
    shl_i_i_i112122_out : OUT STD_LOGIC_VECTOR (31 downto 0);
    shl_i_i_i112122_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of face_accelerate_conv2d_layer_48_6_40_40_1_1_0_false_Pipeline_INIT_TILE_VITIS_LOOP_110_6 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln109_fu_288_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal sext_ln109_cast_fu_266_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln109_cast_reg_608 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal tj_fu_72 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal add_ln110_fu_411_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ti_fu_76 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal select_ln109_1_fu_331_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal indvar_flatten19_fu_80 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal add_ln109_1_fu_294_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_sig_allocacmp_indvar_flatten19_load : STD_LOGIC_VECTOR (4 downto 0);
    signal shl_i_i_i112122_fu_84 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal trunc_ln109_fu_339_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln110_fu_343_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal shl_i_i_i112125_fu_88 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal shl_i_i_i112128_fu_92 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal shl_i_i_i112131_fu_96 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal shl_i_i_i112134_fu_100 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal shl_i_i_i112137_fu_104 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal shl_i_i_i112140_fu_108 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal shl_i_i_i112143_fu_112 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal shl_i_i_i112144_fu_116 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal shl_i_i_i112147_fu_120 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal shl_i_i_i112150_fu_124 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal shl_i_i_i112153_fu_128 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal shl_i_i_i112158_fu_132 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal shl_i_i_i112161_fu_136 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal shl_i_i_i112164_fu_140 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal shl_i_i_i112167_fu_144 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal icmp_ln110_fu_317_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln109_fu_311_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln109_fu_323_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component face_accelerate_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component face_accelerate_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    indvar_flatten19_fu_80_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln109_fu_288_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten19_fu_80 <= add_ln109_1_fu_294_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten19_fu_80 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;

    ti_fu_76_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    ti_fu_76 <= ap_const_lv3_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    ti_fu_76 <= select_ln109_1_fu_331_p3;
                end if;
            end if; 
        end if;
    end process;

    tj_fu_72_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    tj_fu_72 <= ap_const_lv3_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    tj_fu_72 <= add_ln110_fu_411_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                sext_ln109_cast_reg_608 <= sext_ln109_cast_fu_266_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln110_fu_343_p1 = ap_const_lv2_2) and (trunc_ln109_fu_339_p1 = ap_const_lv2_2))) then
                shl_i_i_i112122_fu_84 <= sext_ln109_cast_reg_608;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln110_fu_343_p1 = ap_const_lv2_1) and (trunc_ln109_fu_339_p1 = ap_const_lv2_2))) then
                shl_i_i_i112125_fu_88 <= sext_ln109_cast_reg_608;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln110_fu_343_p1 = ap_const_lv2_0) and (trunc_ln109_fu_339_p1 = ap_const_lv2_2))) then
                shl_i_i_i112128_fu_92 <= sext_ln109_cast_reg_608;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln110_fu_343_p1 = ap_const_lv2_3) and (trunc_ln109_fu_339_p1 = ap_const_lv2_2))) then
                shl_i_i_i112131_fu_96 <= sext_ln109_cast_reg_608;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln110_fu_343_p1 = ap_const_lv2_2) and (trunc_ln109_fu_339_p1 = ap_const_lv2_1))) then
                shl_i_i_i112134_fu_100 <= sext_ln109_cast_reg_608;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln110_fu_343_p1 = ap_const_lv2_1) and (trunc_ln109_fu_339_p1 = ap_const_lv2_1))) then
                shl_i_i_i112137_fu_104 <= sext_ln109_cast_reg_608;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln110_fu_343_p1 = ap_const_lv2_0) and (trunc_ln109_fu_339_p1 = ap_const_lv2_1))) then
                shl_i_i_i112140_fu_108 <= sext_ln109_cast_reg_608;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln110_fu_343_p1 = ap_const_lv2_3) and (trunc_ln109_fu_339_p1 = ap_const_lv2_1))) then
                shl_i_i_i112143_fu_112 <= sext_ln109_cast_reg_608;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln110_fu_343_p1 = ap_const_lv2_2) and (trunc_ln109_fu_339_p1 = ap_const_lv2_0))) then
                shl_i_i_i112144_fu_116 <= sext_ln109_cast_reg_608;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln110_fu_343_p1 = ap_const_lv2_1) and (trunc_ln109_fu_339_p1 = ap_const_lv2_0))) then
                shl_i_i_i112147_fu_120 <= sext_ln109_cast_reg_608;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln110_fu_343_p1 = ap_const_lv2_0) and (trunc_ln109_fu_339_p1 = ap_const_lv2_0))) then
                shl_i_i_i112150_fu_124 <= sext_ln109_cast_reg_608;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln110_fu_343_p1 = ap_const_lv2_3) and (trunc_ln109_fu_339_p1 = ap_const_lv2_0))) then
                shl_i_i_i112153_fu_128 <= sext_ln109_cast_reg_608;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln110_fu_343_p1 = ap_const_lv2_2) and (trunc_ln109_fu_339_p1 = ap_const_lv2_3))) then
                shl_i_i_i112158_fu_132 <= sext_ln109_cast_reg_608;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln110_fu_343_p1 = ap_const_lv2_1) and (trunc_ln109_fu_339_p1 = ap_const_lv2_3))) then
                shl_i_i_i112161_fu_136 <= sext_ln109_cast_reg_608;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln110_fu_343_p1 = ap_const_lv2_0) and (trunc_ln109_fu_339_p1 = ap_const_lv2_3))) then
                shl_i_i_i112164_fu_140 <= sext_ln109_cast_reg_608;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (trunc_ln110_fu_343_p1 = ap_const_lv2_3) and (trunc_ln109_fu_339_p1 = ap_const_lv2_3))) then
                shl_i_i_i112167_fu_144 <= sext_ln109_cast_reg_608;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln109_1_fu_294_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten19_load) + unsigned(ap_const_lv5_1));
    add_ln109_fu_311_p2 <= std_logic_vector(unsigned(ti_fu_76) + unsigned(ap_const_lv3_1));
    add_ln110_fu_411_p2 <= std_logic_vector(unsigned(select_ln109_fu_323_p3) + unsigned(ap_const_lv3_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_01001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln109_fu_288_p2)
    begin
        if (((icmp_ln109_fu_288_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten19_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_init, ap_block_pp0_stage0, indvar_flatten19_fu_80)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten19_load <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_indvar_flatten19_load <= indvar_flatten19_fu_80;
        end if; 
    end process;

    icmp_ln109_fu_288_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten19_load = ap_const_lv5_10) else "0";
    icmp_ln110_fu_317_p2 <= "1" when (tj_fu_72 = ap_const_lv3_4) else "0";
    select_ln109_1_fu_331_p3 <= 
        add_ln109_fu_311_p2 when (icmp_ln110_fu_317_p2(0) = '1') else 
        ti_fu_76;
    select_ln109_fu_323_p3 <= 
        ap_const_lv3_0 when (icmp_ln110_fu_317_p2(0) = '1') else 
        tj_fu_72;
        sext_ln109_cast_fu_266_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(sext_ln109),32));

    shl_i_i_i112122_out <= shl_i_i_i112122_fu_84;

    shl_i_i_i112122_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln109_fu_288_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln109_fu_288_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            shl_i_i_i112122_out_ap_vld <= ap_const_logic_1;
        else 
            shl_i_i_i112122_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    shl_i_i_i112125_out <= shl_i_i_i112125_fu_88;

    shl_i_i_i112125_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln109_fu_288_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln109_fu_288_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            shl_i_i_i112125_out_ap_vld <= ap_const_logic_1;
        else 
            shl_i_i_i112125_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    shl_i_i_i112128_out <= shl_i_i_i112128_fu_92;

    shl_i_i_i112128_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln109_fu_288_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln109_fu_288_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            shl_i_i_i112128_out_ap_vld <= ap_const_logic_1;
        else 
            shl_i_i_i112128_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    shl_i_i_i112131_out <= shl_i_i_i112131_fu_96;

    shl_i_i_i112131_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln109_fu_288_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln109_fu_288_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            shl_i_i_i112131_out_ap_vld <= ap_const_logic_1;
        else 
            shl_i_i_i112131_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    shl_i_i_i112134_out <= shl_i_i_i112134_fu_100;

    shl_i_i_i112134_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln109_fu_288_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln109_fu_288_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            shl_i_i_i112134_out_ap_vld <= ap_const_logic_1;
        else 
            shl_i_i_i112134_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    shl_i_i_i112137_out <= shl_i_i_i112137_fu_104;

    shl_i_i_i112137_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln109_fu_288_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln109_fu_288_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            shl_i_i_i112137_out_ap_vld <= ap_const_logic_1;
        else 
            shl_i_i_i112137_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    shl_i_i_i112140_out <= shl_i_i_i112140_fu_108;

    shl_i_i_i112140_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln109_fu_288_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln109_fu_288_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            shl_i_i_i112140_out_ap_vld <= ap_const_logic_1;
        else 
            shl_i_i_i112140_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    shl_i_i_i112143_out <= shl_i_i_i112143_fu_112;

    shl_i_i_i112143_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln109_fu_288_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln109_fu_288_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            shl_i_i_i112143_out_ap_vld <= ap_const_logic_1;
        else 
            shl_i_i_i112143_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    shl_i_i_i112144_out <= shl_i_i_i112144_fu_116;

    shl_i_i_i112144_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln109_fu_288_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln109_fu_288_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            shl_i_i_i112144_out_ap_vld <= ap_const_logic_1;
        else 
            shl_i_i_i112144_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    shl_i_i_i112147_out <= shl_i_i_i112147_fu_120;

    shl_i_i_i112147_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln109_fu_288_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln109_fu_288_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            shl_i_i_i112147_out_ap_vld <= ap_const_logic_1;
        else 
            shl_i_i_i112147_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    shl_i_i_i112150_out <= shl_i_i_i112150_fu_124;

    shl_i_i_i112150_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln109_fu_288_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln109_fu_288_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            shl_i_i_i112150_out_ap_vld <= ap_const_logic_1;
        else 
            shl_i_i_i112150_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    shl_i_i_i112153_out <= shl_i_i_i112153_fu_128;

    shl_i_i_i112153_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln109_fu_288_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln109_fu_288_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            shl_i_i_i112153_out_ap_vld <= ap_const_logic_1;
        else 
            shl_i_i_i112153_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    shl_i_i_i112158_out <= shl_i_i_i112158_fu_132;

    shl_i_i_i112158_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln109_fu_288_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln109_fu_288_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            shl_i_i_i112158_out_ap_vld <= ap_const_logic_1;
        else 
            shl_i_i_i112158_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    shl_i_i_i112161_out <= shl_i_i_i112161_fu_136;

    shl_i_i_i112161_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln109_fu_288_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln109_fu_288_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            shl_i_i_i112161_out_ap_vld <= ap_const_logic_1;
        else 
            shl_i_i_i112161_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    shl_i_i_i112164_out <= shl_i_i_i112164_fu_140;

    shl_i_i_i112164_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln109_fu_288_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln109_fu_288_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            shl_i_i_i112164_out_ap_vld <= ap_const_logic_1;
        else 
            shl_i_i_i112164_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    shl_i_i_i112167_out <= shl_i_i_i112167_fu_144;

    shl_i_i_i112167_out_ap_vld_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln109_fu_288_p2, ap_loop_exit_ready, ap_block_pp0_stage0_11001)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln109_fu_288_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            shl_i_i_i112167_out_ap_vld <= ap_const_logic_1;
        else 
            shl_i_i_i112167_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln109_fu_339_p1 <= select_ln109_1_fu_331_p3(2 - 1 downto 0);
    trunc_ln110_fu_343_p1 <= select_ln109_fu_323_p3(2 - 1 downto 0);
end behav;
