-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity face_accelerate_conv2d_layer_Pipeline_WRITE_TILE_VITIS_LOOP_200_12 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem0_AWREADY : IN STD_LOGIC;
    m_axi_gmem0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_WVALID : OUT STD_LOGIC;
    m_axi_gmem0_WREADY : IN STD_LOGIC;
    m_axi_gmem0_WDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
    m_axi_gmem0_WSTRB : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_WLAST : OUT STD_LOGIC;
    m_axi_gmem0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem0_ARREADY : IN STD_LOGIC;
    m_axi_gmem0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_RVALID : IN STD_LOGIC;
    m_axi_gmem0_RREADY : OUT STD_LOGIC;
    m_axi_gmem0_RDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    m_axi_gmem0_RLAST : IN STD_LOGIC;
    m_axi_gmem0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_RFIFONUM : IN STD_LOGIC_VECTOR (9 downto 0);
    m_axi_gmem0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_BVALID : IN STD_LOGIC;
    m_axi_gmem0_BREADY : OUT STD_LOGIC;
    m_axi_gmem0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    empty_53 : IN STD_LOGIC_VECTOR (21 downto 0);
    empty_54 : IN STD_LOGIC_VECTOR (21 downto 0);
    empty_55 : IN STD_LOGIC_VECTOR (21 downto 0);
    empty_56 : IN STD_LOGIC_VECTOR (21 downto 0);
    empty_57 : IN STD_LOGIC_VECTOR (21 downto 0);
    empty_58 : IN STD_LOGIC_VECTOR (21 downto 0);
    empty_59 : IN STD_LOGIC_VECTOR (21 downto 0);
    empty_60 : IN STD_LOGIC_VECTOR (21 downto 0);
    empty_61 : IN STD_LOGIC_VECTOR (21 downto 0);
    empty_62 : IN STD_LOGIC_VECTOR (21 downto 0);
    empty_63 : IN STD_LOGIC_VECTOR (21 downto 0);
    empty_64 : IN STD_LOGIC_VECTOR (21 downto 0);
    empty_65 : IN STD_LOGIC_VECTOR (21 downto 0);
    empty_66 : IN STD_LOGIC_VECTOR (21 downto 0);
    empty_67 : IN STD_LOGIC_VECTOR (21 downto 0);
    empty : IN STD_LOGIC_VECTOR (21 downto 0);
    add_ln79 : IN STD_LOGIC_VECTOR (10 downto 0);
    phi_mul : IN STD_LOGIC_VECTOR (13 downto 0);
    output_r : IN STD_LOGIC_VECTOR (63 downto 0) );
end;


architecture behav of face_accelerate_conv2d_layer_Pipeline_WRITE_TILE_VITIS_LOOP_200_12 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv64_4 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000100";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal first_iter_3_reg_693 : STD_LOGIC_VECTOR (0 downto 0);
    signal first_iter_3_reg_693_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state4_io : BOOLEAN;
    signal icmp_ln200_1_reg_707 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln200_1_reg_707_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state10_pp0_stage0_iter9 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln199_fu_288_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem0_blk_n_B : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal gmem0_blk_n_W : STD_LOGIC;
    signal gmem0_blk_n_AW : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal first_iter_3_fu_339_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_91_fu_369_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal empty_91_reg_697 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln7_reg_702 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln7_reg_702_pp0_iter2_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln7_reg_702_pp0_iter3_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln200_1_fu_503_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln200_1_reg_707_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln200_1_reg_707_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln200_1_reg_707_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln200_1_reg_707_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln200_1_reg_707_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln200_1_reg_707_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal gmem0_addr_reg_711 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln200_fu_563_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal tj_fu_128 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal add_ln200_fu_497_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ti_fu_132 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal select_ln199_1_fu_331_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal indvar_flatten26_fu_136 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal add_ln199_1_fu_294_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_sig_allocacmp_indvar_flatten26_load : STD_LOGIC_VECTOR (4 downto 0);
    signal icmp_ln200_fu_317_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln199_fu_311_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln199_fu_323_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_40_fu_345_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_41_fu_357_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_shl_fu_353_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_shl10_fu_365_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_fu_383_p9 : STD_LOGIC_VECTOR (21 downto 0);
    signal trunc_ln200_fu_379_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_fu_403_p9 : STD_LOGIC_VECTOR (21 downto 0);
    signal tmp_2_fu_423_p9 : STD_LOGIC_VECTOR (21 downto 0);
    signal tmp_3_fu_443_p9 : STD_LOGIC_VECTOR (21 downto 0);
    signal tmp_fu_383_p11 : STD_LOGIC_VECTOR (21 downto 0);
    signal tmp_1_fu_403_p11 : STD_LOGIC_VECTOR (21 downto 0);
    signal tmp_2_fu_423_p11 : STD_LOGIC_VECTOR (21 downto 0);
    signal tmp_3_fu_443_p11 : STD_LOGIC_VECTOR (21 downto 0);
    signal value_fu_463_p9 : STD_LOGIC_VECTOR (21 downto 0);
    signal value_fu_463_p10 : STD_LOGIC_VECTOR (1 downto 0);
    signal value_fu_463_p11 : STD_LOGIC_VECTOR (21 downto 0);
    signal p_cast6_fu_519_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp2_fu_522_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp2_cast_fu_527_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal empty_92_fu_531_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_s_fu_536_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_cast12_fu_544_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal empty_93_fu_548_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln5_fu_553_p4 : STD_LOGIC_VECTOR (62 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal tmp_fu_383_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_383_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_383_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_fu_383_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_fu_403_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_fu_403_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_fu_403_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_fu_403_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_2_fu_423_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_2_fu_423_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_2_fu_423_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_2_fu_423_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_3_fu_443_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_3_fu_443_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_3_fu_443_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_3_fu_443_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal value_fu_463_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal value_fu_463_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal value_fu_463_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal value_fu_463_p7 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component face_accelerate_sparsemux_9_2_22_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (1 downto 0);
        din3_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (21 downto 0);
        din1 : IN STD_LOGIC_VECTOR (21 downto 0);
        din2 : IN STD_LOGIC_VECTOR (21 downto 0);
        din3 : IN STD_LOGIC_VECTOR (21 downto 0);
        def : IN STD_LOGIC_VECTOR (21 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (21 downto 0) );
    end component;


    component face_accelerate_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    sparsemux_9_2_22_1_1_U706 : component face_accelerate_sparsemux_9_2_22_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 22,
        CASE1 => "01",
        din1_WIDTH => 22,
        CASE2 => "10",
        din2_WIDTH => 22,
        CASE3 => "11",
        din3_WIDTH => 22,
        def_WIDTH => 22,
        sel_WIDTH => 2,
        dout_WIDTH => 22)
    port map (
        din0 => empty_53,
        din1 => empty_54,
        din2 => empty_55,
        din3 => empty_56,
        def => tmp_fu_383_p9,
        sel => trunc_ln200_fu_379_p1,
        dout => tmp_fu_383_p11);

    sparsemux_9_2_22_1_1_U707 : component face_accelerate_sparsemux_9_2_22_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 22,
        CASE1 => "01",
        din1_WIDTH => 22,
        CASE2 => "10",
        din2_WIDTH => 22,
        CASE3 => "11",
        din3_WIDTH => 22,
        def_WIDTH => 22,
        sel_WIDTH => 2,
        dout_WIDTH => 22)
    port map (
        din0 => empty_57,
        din1 => empty_58,
        din2 => empty_59,
        din3 => empty_60,
        def => tmp_1_fu_403_p9,
        sel => trunc_ln200_fu_379_p1,
        dout => tmp_1_fu_403_p11);

    sparsemux_9_2_22_1_1_U708 : component face_accelerate_sparsemux_9_2_22_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 22,
        CASE1 => "01",
        din1_WIDTH => 22,
        CASE2 => "10",
        din2_WIDTH => 22,
        CASE3 => "11",
        din3_WIDTH => 22,
        def_WIDTH => 22,
        sel_WIDTH => 2,
        dout_WIDTH => 22)
    port map (
        din0 => empty_61,
        din1 => empty_62,
        din2 => empty_63,
        din3 => empty_64,
        def => tmp_2_fu_423_p9,
        sel => trunc_ln200_fu_379_p1,
        dout => tmp_2_fu_423_p11);

    sparsemux_9_2_22_1_1_U709 : component face_accelerate_sparsemux_9_2_22_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 22,
        CASE1 => "01",
        din1_WIDTH => 22,
        CASE2 => "10",
        din2_WIDTH => 22,
        CASE3 => "11",
        din3_WIDTH => 22,
        def_WIDTH => 22,
        sel_WIDTH => 2,
        dout_WIDTH => 22)
    port map (
        din0 => empty_65,
        din1 => empty_66,
        din2 => empty_67,
        din3 => empty,
        def => tmp_3_fu_443_p9,
        sel => trunc_ln200_fu_379_p1,
        dout => tmp_3_fu_443_p11);

    sparsemux_9_2_22_1_1_U710 : component face_accelerate_sparsemux_9_2_22_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00",
        din0_WIDTH => 22,
        CASE1 => "01",
        din1_WIDTH => 22,
        CASE2 => "10",
        din2_WIDTH => 22,
        CASE3 => "11",
        din3_WIDTH => 22,
        def_WIDTH => 22,
        sel_WIDTH => 2,
        dout_WIDTH => 22)
    port map (
        din0 => tmp_fu_383_p11,
        din1 => tmp_1_fu_403_p11,
        din2 => tmp_2_fu_423_p11,
        din3 => tmp_3_fu_443_p11,
        def => value_fu_463_p9,
        sel => value_fu_463_p10,
        dout => value_fu_463_p11);

    flow_control_loop_pipe_sequential_init_U : component face_accelerate_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter8_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    indvar_flatten26_fu_136_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln199_fu_288_p2 = ap_const_lv1_0))) then 
                    indvar_flatten26_fu_136 <= add_ln199_1_fu_294_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten26_fu_136 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;

    ti_fu_132_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    ti_fu_132 <= ap_const_lv3_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    ti_fu_132 <= select_ln199_1_fu_331_p3;
                end if;
            end if; 
        end if;
    end process;

    tj_fu_128_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    tj_fu_128 <= ap_const_lv3_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    tj_fu_128 <= add_ln200_fu_497_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                    empty_91_reg_697(8 downto 3) <= empty_91_fu_369_p2(8 downto 3);
                first_iter_3_reg_693 <= first_iter_3_fu_339_p2;
                icmp_ln200_1_reg_707 <= icmp_ln200_1_fu_503_p2;
                trunc_ln7_reg_702 <= value_fu_463_p11(21 downto 6);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                first_iter_3_reg_693_pp0_iter2_reg <= first_iter_3_reg_693;
                gmem0_addr_reg_711 <= sext_ln200_fu_563_p1;
                icmp_ln200_1_reg_707_pp0_iter2_reg <= icmp_ln200_1_reg_707;
                icmp_ln200_1_reg_707_pp0_iter3_reg <= icmp_ln200_1_reg_707_pp0_iter2_reg;
                icmp_ln200_1_reg_707_pp0_iter4_reg <= icmp_ln200_1_reg_707_pp0_iter3_reg;
                icmp_ln200_1_reg_707_pp0_iter5_reg <= icmp_ln200_1_reg_707_pp0_iter4_reg;
                icmp_ln200_1_reg_707_pp0_iter6_reg <= icmp_ln200_1_reg_707_pp0_iter5_reg;
                icmp_ln200_1_reg_707_pp0_iter7_reg <= icmp_ln200_1_reg_707_pp0_iter6_reg;
                icmp_ln200_1_reg_707_pp0_iter8_reg <= icmp_ln200_1_reg_707_pp0_iter7_reg;
                trunc_ln7_reg_702_pp0_iter2_reg <= trunc_ln7_reg_702;
                trunc_ln7_reg_702_pp0_iter3_reg <= trunc_ln7_reg_702_pp0_iter2_reg;
            end if;
        end if;
    end process;
    empty_91_reg_697(2 downto 0) <= "000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln199_1_fu_294_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten26_load) + unsigned(ap_const_lv5_1));
    add_ln199_fu_311_p2 <= std_logic_vector(unsigned(ti_fu_132) + unsigned(ap_const_lv3_1));
    add_ln200_fu_497_p2 <= std_logic_vector(unsigned(select_ln199_fu_323_p3) + unsigned(ap_const_lv3_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter9, ap_block_state10_pp0_stage0_iter9)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state10_pp0_stage0_iter9));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter9, m_axi_gmem0_WREADY, ap_block_state4_io, ap_block_state10_pp0_stage0_iter9)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state10_pp0_stage0_iter9)) or ((m_axi_gmem0_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_io)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter9, m_axi_gmem0_WREADY, ap_block_state4_io, ap_block_state10_pp0_stage0_iter9)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state10_pp0_stage0_iter9)) or ((m_axi_gmem0_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state4_io)));
    end process;


    ap_block_state10_pp0_stage0_iter9_assign_proc : process(m_axi_gmem0_BVALID, icmp_ln200_1_reg_707_pp0_iter8_reg)
    begin
                ap_block_state10_pp0_stage0_iter9 <= ((icmp_ln200_1_reg_707_pp0_iter8_reg = ap_const_lv1_1) and (m_axi_gmem0_BVALID = ap_const_logic_0));
    end process;


    ap_block_state4_io_assign_proc : process(m_axi_gmem0_AWREADY, first_iter_3_reg_693_pp0_iter2_reg)
    begin
                ap_block_state4_io <= ((m_axi_gmem0_AWREADY = ap_const_logic_0) and (first_iter_3_reg_693_pp0_iter2_reg = ap_const_lv1_1));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln199_fu_288_p2)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln199_fu_288_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter8_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter8_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9)
    begin
        if (((ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten26_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten26_fu_136)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten26_load <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_indvar_flatten26_load <= indvar_flatten26_fu_136;
        end if; 
    end process;

    empty_91_fu_369_p2 <= std_logic_vector(unsigned(p_shl_fu_353_p1) + unsigned(p_shl10_fu_365_p1));
    empty_92_fu_531_p2 <= std_logic_vector(unsigned(tmp2_cast_fu_527_p1) + unsigned(phi_mul));
    empty_93_fu_548_p2 <= std_logic_vector(unsigned(p_cast12_fu_544_p1) + unsigned(output_r));
    first_iter_3_fu_339_p2 <= "1" when (select_ln199_fu_323_p3 = ap_const_lv3_0) else "0";

    gmem0_blk_n_AW_assign_proc : process(ap_enable_reg_pp0_iter3, m_axi_gmem0_AWREADY, first_iter_3_reg_693_pp0_iter2_reg, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (first_iter_3_reg_693_pp0_iter2_reg = ap_const_lv1_1))) then 
            gmem0_blk_n_AW <= m_axi_gmem0_AWREADY;
        else 
            gmem0_blk_n_AW <= ap_const_logic_1;
        end if; 
    end process;


    gmem0_blk_n_B_assign_proc : process(ap_enable_reg_pp0_iter9, m_axi_gmem0_BVALID, icmp_ln200_1_reg_707_pp0_iter8_reg, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (icmp_ln200_1_reg_707_pp0_iter8_reg = ap_const_lv1_1))) then 
            gmem0_blk_n_B <= m_axi_gmem0_BVALID;
        else 
            gmem0_blk_n_B <= ap_const_logic_1;
        end if; 
    end process;


    gmem0_blk_n_W_assign_proc : process(ap_enable_reg_pp0_iter4, m_axi_gmem0_WREADY, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            gmem0_blk_n_W <= m_axi_gmem0_WREADY;
        else 
            gmem0_blk_n_W <= ap_const_logic_1;
        end if; 
    end process;

    icmp_ln199_fu_288_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten26_load = ap_const_lv5_10) else "0";
    icmp_ln200_1_fu_503_p2 <= "1" when (add_ln200_fu_497_p2 = ap_const_lv3_4) else "0";
    icmp_ln200_fu_317_p2 <= "1" when (tj_fu_128 = ap_const_lv3_4) else "0";
    m_axi_gmem0_ARADDR <= ap_const_lv64_0;
    m_axi_gmem0_ARBURST <= ap_const_lv2_0;
    m_axi_gmem0_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem0_ARID <= ap_const_lv1_0;
    m_axi_gmem0_ARLEN <= ap_const_lv32_0;
    m_axi_gmem0_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem0_ARPROT <= ap_const_lv3_0;
    m_axi_gmem0_ARQOS <= ap_const_lv4_0;
    m_axi_gmem0_ARREGION <= ap_const_lv4_0;
    m_axi_gmem0_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem0_ARUSER <= ap_const_lv1_0;
    m_axi_gmem0_ARVALID <= ap_const_logic_0;
    m_axi_gmem0_AWADDR <= gmem0_addr_reg_711;
    m_axi_gmem0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem0_AWID <= ap_const_lv1_0;
    m_axi_gmem0_AWLEN <= ap_const_lv64_4(32 - 1 downto 0);
    m_axi_gmem0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem0_AWUSER <= ap_const_lv1_0;

    m_axi_gmem0_AWVALID_assign_proc : process(ap_enable_reg_pp0_iter3, first_iter_3_reg_693_pp0_iter2_reg, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (first_iter_3_reg_693_pp0_iter2_reg = ap_const_lv1_1))) then 
            m_axi_gmem0_AWVALID <= ap_const_logic_1;
        else 
            m_axi_gmem0_AWVALID <= ap_const_logic_0;
        end if; 
    end process;


    m_axi_gmem0_BREADY_assign_proc : process(ap_enable_reg_pp0_iter9, icmp_ln200_1_reg_707_pp0_iter8_reg, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln200_1_reg_707_pp0_iter8_reg = ap_const_lv1_1))) then 
            m_axi_gmem0_BREADY <= ap_const_logic_1;
        else 
            m_axi_gmem0_BREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem0_RREADY <= ap_const_logic_0;
    m_axi_gmem0_WDATA <= trunc_ln7_reg_702_pp0_iter3_reg;
    m_axi_gmem0_WID <= ap_const_lv1_0;
    m_axi_gmem0_WLAST <= ap_const_logic_0;
    m_axi_gmem0_WSTRB <= ap_const_lv2_3;
    m_axi_gmem0_WUSER <= ap_const_lv1_0;

    m_axi_gmem0_WVALID_assign_proc : process(ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            m_axi_gmem0_WVALID <= ap_const_logic_1;
        else 
            m_axi_gmem0_WVALID <= ap_const_logic_0;
        end if; 
    end process;

    p_cast12_fu_544_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_536_p3),64));
    p_cast6_fu_519_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_91_reg_697),11));
    p_shl10_fu_365_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_41_fu_357_p3),9));
    p_shl_fu_353_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_40_fu_345_p3),9));
    select_ln199_1_fu_331_p3 <= 
        add_ln199_fu_311_p2 when (icmp_ln200_fu_317_p2(0) = '1') else 
        ti_fu_132;
    select_ln199_fu_323_p3 <= 
        ap_const_lv3_0 when (icmp_ln200_fu_317_p2(0) = '1') else 
        tj_fu_128;
        sext_ln200_fu_563_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln5_fu_553_p4),64));

    tmp2_cast_fu_527_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp2_fu_522_p2),14));
    tmp2_fu_522_p2 <= std_logic_vector(unsigned(add_ln79) + unsigned(p_cast6_fu_519_p1));
    tmp_1_fu_403_p9 <= "XXXXXXXXXXXXXXXXXXXXXX";
    tmp_2_fu_423_p9 <= "XXXXXXXXXXXXXXXXXXXXXX";
    tmp_3_fu_443_p9 <= "XXXXXXXXXXXXXXXXXXXXXX";
    tmp_40_fu_345_p3 <= (select_ln199_1_fu_331_p3 & ap_const_lv5_0);
    tmp_41_fu_357_p3 <= (select_ln199_1_fu_331_p3 & ap_const_lv3_0);
    tmp_fu_383_p9 <= "XXXXXXXXXXXXXXXXXXXXXX";
    tmp_s_fu_536_p3 <= (empty_92_fu_531_p2 & ap_const_lv1_0);
    trunc_ln200_fu_379_p1 <= select_ln199_fu_323_p3(2 - 1 downto 0);
    trunc_ln5_fu_553_p4 <= empty_93_fu_548_p2(63 downto 1);
    value_fu_463_p10 <= select_ln199_1_fu_331_p3(2 - 1 downto 0);
    value_fu_463_p9 <= "XXXXXXXXXXXXXXXXXXXXXX";
end behav;
