-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity face_accelerate_conv2d_layer_Pipeline_LOAD_TILE_VITIS_LOOP_85_3_VITIS_LOOP_86_4_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    m_axi_gmem0_AWVALID : OUT STD_LOGIC;
    m_axi_gmem0_AWREADY : IN STD_LOGIC;
    m_axi_gmem0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_WVALID : OUT STD_LOGIC;
    m_axi_gmem0_WREADY : IN STD_LOGIC;
    m_axi_gmem0_WDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
    m_axi_gmem0_WSTRB : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_WLAST : OUT STD_LOGIC;
    m_axi_gmem0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_ARVALID : OUT STD_LOGIC;
    m_axi_gmem0_ARREADY : IN STD_LOGIC;
    m_axi_gmem0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_gmem0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_gmem0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_RVALID : IN STD_LOGIC;
    m_axi_gmem0_RREADY : OUT STD_LOGIC;
    m_axi_gmem0_RDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    m_axi_gmem0_RLAST : IN STD_LOGIC;
    m_axi_gmem0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_RFIFONUM : IN STD_LOGIC_VECTOR (9 downto 0);
    m_axi_gmem0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_BVALID : IN STD_LOGIC;
    m_axi_gmem0_BREADY : OUT STD_LOGIC;
    m_axi_gmem0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_gmem0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    zext_ln73 : IN STD_LOGIC_VECTOR (8 downto 0);
    input_tile_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    input_tile_ce0 : OUT STD_LOGIC;
    input_tile_we0 : OUT STD_LOGIC;
    input_tile_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_tile_9_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    input_tile_9_ce0 : OUT STD_LOGIC;
    input_tile_9_we0 : OUT STD_LOGIC;
    input_tile_9_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_tile_10_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    input_tile_10_ce0 : OUT STD_LOGIC;
    input_tile_10_we0 : OUT STD_LOGIC;
    input_tile_10_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_tile_11_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    input_tile_11_ce0 : OUT STD_LOGIC;
    input_tile_11_we0 : OUT STD_LOGIC;
    input_tile_11_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_tile_12_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    input_tile_12_ce0 : OUT STD_LOGIC;
    input_tile_12_we0 : OUT STD_LOGIC;
    input_tile_12_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_tile_13_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    input_tile_13_ce0 : OUT STD_LOGIC;
    input_tile_13_we0 : OUT STD_LOGIC;
    input_tile_13_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_tile_14_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    input_tile_14_ce0 : OUT STD_LOGIC;
    input_tile_14_we0 : OUT STD_LOGIC;
    input_tile_14_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_tile_15_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    input_tile_15_ce0 : OUT STD_LOGIC;
    input_tile_15_we0 : OUT STD_LOGIC;
    input_tile_15_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    input_tile_16_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    input_tile_16_ce0 : OUT STD_LOGIC;
    input_tile_16_we0 : OUT STD_LOGIC;
    input_tile_16_d0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    zext_ln84 : IN STD_LOGIC_VECTOR (8 downto 0);
    input_r : IN STD_LOGIC_VECTOR (63 downto 0) );
end;


architecture behav of face_accelerate_conv2d_layer_Pipeline_LOAD_TILE_VITIS_LOOP_85_3_VITIS_LOOP_86_4_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv64_1 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000001";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv8_F3 : STD_LOGIC_VECTOR (7 downto 0) := "11110011";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv8_51 : STD_LOGIC_VECTOR (7 downto 0) := "01010001";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv9_16 : STD_LOGIC_VECTOR (8 downto 0) := "000010110";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv10_140 : STD_LOGIC_VECTOR (9 downto 0) := "0101000000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv19_19000 : STD_LOGIC_VECTOR (18 downto 0) := "0011001000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter14 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal icmp_ln84_reg_808 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_808_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln92_reg_868 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln92_reg_868_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op120_readreq_state6 : BOOLEAN;
    signal ap_block_state6_io : BOOLEAN;
    signal icmp_ln84_reg_808_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln92_reg_868_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op143_read_state14 : BOOLEAN;
    signal ap_block_state14_pp0_stage0_iter13 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln84_fu_354_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal gmem0_blk_n_AR : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal gmem0_blk_n_R : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal zext_ln84_cast_fu_315_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln84_cast_reg_798 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln73_cast_fu_319_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln73_cast_reg_803 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln84_reg_808_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_808_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_808_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_808_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_808_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_808_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_808_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_808_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_808_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_808_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln84_reg_808_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln85_fu_375_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln85_reg_812 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln84_3_fu_381_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln84_3_reg_819 : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln84_3_reg_819_pp0_iter1_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal select_ln84_3_reg_819_pp0_iter2_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tx_mid2_fu_463_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tx_mid2_reg_830 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln85_fu_471_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln85_reg_837 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp1_fu_485_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp1_reg_843 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_reg_848 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_56_reg_858 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln89_fu_612_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal add_ln89_reg_863 : STD_LOGIC_VECTOR (9 downto 0);
    signal and_ln92_fu_623_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln92_reg_868_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln92_reg_868_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln92_reg_868_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln92_reg_868_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln92_reg_868_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln92_reg_868_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln92_reg_868_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln92_reg_868_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln92_reg_868_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln95_3_fu_679_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln95_3_reg_872 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln95_3_reg_872_pp0_iter4_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln95_3_reg_872_pp0_iter5_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln95_3_reg_872_pp0_iter6_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln95_3_reg_872_pp0_iter7_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln95_3_reg_872_pp0_iter8_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln95_3_reg_872_pp0_iter9_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln95_3_reg_872_pp0_iter10_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln95_3_reg_872_pp0_iter11_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln95_3_reg_872_pp0_iter12_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln95_3_reg_872_pp0_iter13_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln93_fu_688_p2 : STD_LOGIC_VECTOR (18 downto 0);
    attribute use_dsp48 : string;
    attribute use_dsp48 of add_ln93_fu_688_p2 : signal is "no";
    signal add_ln93_reg_877 : STD_LOGIC_VECTOR (18 downto 0);
    signal gmem0_addr_reg_882 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln85_fu_729_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln85_reg_888 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln85_reg_888_pp0_iter9_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln85_reg_888_pp0_iter10_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln85_reg_888_pp0_iter11_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln85_reg_888_pp0_iter12_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln85_reg_888_pp0_iter13_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln86_fu_733_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln86_reg_892 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln86_reg_892_pp0_iter9_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln86_reg_892_pp0_iter10_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln86_reg_892_pp0_iter11_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln86_reg_892_pp0_iter12_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln86_reg_892_pp0_iter13_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal v_reg_896 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_v_2_phi_fu_299_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter14_v_2_reg_295 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter0_v_2_reg_295 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter1_v_2_reg_295 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter2_v_2_reg_295 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter3_v_2_reg_295 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter4_v_2_reg_295 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter5_v_2_reg_295 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter6_v_2_reg_295 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter7_v_2_reg_295 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter8_v_2_reg_295 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter9_v_2_reg_295 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter10_v_2_reg_295 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter11_v_2_reg_295 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter12_v_2_reg_295 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter13_v_2_reg_295 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln95_11_fu_737_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln93_fu_719_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tx_fu_128 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal add_ln86_fu_497_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ty_fu_132 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    signal indvar_flatten_fu_136 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal select_ln85_3_fu_399_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_sig_allocacmp_indvar_flatten_load : STD_LOGIC_VECTOR (7 downto 0);
    signal ic_fu_140 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal ap_sig_allocacmp_ic_load : STD_LOGIC_VECTOR (1 downto 0);
    signal indvar_flatten12_fu_144 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal add_ln84_3_fu_360_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_sig_allocacmp_indvar_flatten12_load : STD_LOGIC_VECTOR (7 downto 0);
    signal input_tile_12_we0_local : STD_LOGIC;
    signal input_tile_12_ce0_local : STD_LOGIC;
    signal input_tile_11_we0_local : STD_LOGIC;
    signal input_tile_11_ce0_local : STD_LOGIC;
    signal input_tile_13_we0_local : STD_LOGIC;
    signal input_tile_13_ce0_local : STD_LOGIC;
    signal input_tile_9_we0_local : STD_LOGIC;
    signal input_tile_9_ce0_local : STD_LOGIC;
    signal input_tile_we0_local : STD_LOGIC;
    signal input_tile_ce0_local : STD_LOGIC;
    signal input_tile_10_we0_local : STD_LOGIC;
    signal input_tile_10_ce0_local : STD_LOGIC;
    signal input_tile_15_we0_local : STD_LOGIC;
    signal input_tile_15_ce0_local : STD_LOGIC;
    signal input_tile_14_we0_local : STD_LOGIC;
    signal input_tile_14_ce0_local : STD_LOGIC;
    signal input_tile_16_we0_local : STD_LOGIC;
    signal input_tile_16_ce0_local : STD_LOGIC;
    signal add_ln84_fu_369_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal add_ln85_3_fu_393_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln86_fu_440_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln84_fu_435_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln84_fu_428_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal and_ln84_fu_446_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_fu_458_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln85_fu_452_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_479_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_fu_491_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal mul_ln85_fu_516_p0 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln85_fu_516_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal mul_ln85_fu_516_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp1_cast_fu_532_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal empty_104_fu_535_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_53_fu_540_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_54_fu_554_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_55_fu_566_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_shl_fu_562_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal p_shl21_fu_574_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal mul_ln86_fu_587_p0 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_ln86_fu_587_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal mul_ln86_fu_587_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln89_2_fu_603_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal sext_ln89_fu_608_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal icmp_ln92_fu_617_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal rev_fu_548_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_shl3_fu_632_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln95_fu_629_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal sub_ln95_fu_639_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln85_2_fu_645_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln95_fu_648_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln95_fu_654_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_52_fu_658_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln95_9_fu_666_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal sub_ln85_fu_670_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln95_10_fu_676_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal add_ln93_fu_688_p0 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_fu_749_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal zext_ln93_fu_685_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal shl_ln_fu_693_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal zext_ln93_2_fu_700_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal add_ln93_2_fu_704_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln_fu_709_p4 : STD_LOGIC_VECTOR (62 downto 0);
    signal grp_fu_479_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_fu_491_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_fu_749_p0 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_fu_749_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_fu_749_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_fu_479_ce : STD_LOGIC;
    signal grp_fu_491_ce : STD_LOGIC;
    signal grp_fu_749_ce : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter11_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter12_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter13_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal grp_fu_749_p10 : STD_LOGIC_VECTOR (18 downto 0);
    signal mul_ln85_fu_516_p00 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln86_fu_587_p00 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component face_accelerate_urem_4ns_3ns_2_8_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (3 downto 0);
        din1 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (1 downto 0) );
    end component;


    component face_accelerate_mul_4ns_6ns_9_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (3 downto 0);
        din1 : IN STD_LOGIC_VECTOR (5 downto 0);
        dout : OUT STD_LOGIC_VECTOR (8 downto 0) );
    end component;


    component face_accelerate_mac_muladd_17ns_2ns_19s_19_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (16 downto 0);
        din1 : IN STD_LOGIC_VECTOR (1 downto 0);
        din2 : IN STD_LOGIC_VECTOR (18 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (18 downto 0) );
    end component;


    component face_accelerate_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    urem_4ns_3ns_2_8_1_U1 : component face_accelerate_urem_4ns_3ns_2_8_1
    generic map (
        ID => 1,
        NUM_STAGE => 8,
        din0_WIDTH => 4,
        din1_WIDTH => 3,
        dout_WIDTH => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => select_ln85_fu_471_p3,
        din1 => grp_fu_479_p1,
        ce => grp_fu_479_ce,
        dout => grp_fu_479_p2);

    urem_4ns_3ns_2_8_1_U2 : component face_accelerate_urem_4ns_3ns_2_8_1
    generic map (
        ID => 1,
        NUM_STAGE => 8,
        din0_WIDTH => 4,
        din1_WIDTH => 3,
        dout_WIDTH => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => tx_mid2_fu_463_p3,
        din1 => grp_fu_491_p1,
        ce => grp_fu_491_ce,
        dout => grp_fu_491_p2);

    mul_4ns_6ns_9_1_1_U3 : component face_accelerate_mul_4ns_6ns_9_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 6,
        dout_WIDTH => 9)
    port map (
        din0 => mul_ln85_fu_516_p0,
        din1 => mul_ln85_fu_516_p1,
        dout => mul_ln85_fu_516_p2);

    mul_4ns_6ns_9_1_1_U4 : component face_accelerate_mul_4ns_6ns_9_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 4,
        din1_WIDTH => 6,
        dout_WIDTH => 9)
    port map (
        din0 => mul_ln86_fu_587_p0,
        din1 => mul_ln86_fu_587_p1,
        dout => mul_ln86_fu_587_p2);

    mac_muladd_17ns_2ns_19s_19_4_1_U5 : component face_accelerate_mac_muladd_17ns_2ns_19s_19_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 17,
        din1_WIDTH => 2,
        din2_WIDTH => 19,
        dout_WIDTH => 19)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_749_p0,
        din1 => grp_fu_749_p1,
        din2 => grp_fu_749_p2,
        ce => grp_fu_749_ce,
        dout => grp_fu_749_p3);

    flow_control_loop_pipe_sequential_init_U : component face_accelerate_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter13_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter14_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter14 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter4_v_2_reg_295_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((icmp_ln84_reg_808_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln92_reg_868))) then 
                    ap_phi_reg_pp0_iter4_v_2_reg_295 <= ap_const_lv16_0;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter4_v_2_reg_295 <= ap_phi_reg_pp0_iter3_v_2_reg_295;
                end if;
            end if; 
        end if;
    end process;

    ic_fu_140_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln84_fu_354_p2 = ap_const_lv1_0))) then 
                    ic_fu_140 <= select_ln84_3_fu_381_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    ic_fu_140 <= ap_const_lv2_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten12_fu_144_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln84_fu_354_p2 = ap_const_lv1_0))) then 
                    indvar_flatten12_fu_144 <= add_ln84_3_fu_360_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten12_fu_144 <= ap_const_lv8_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_136_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln84_fu_354_p2 = ap_const_lv1_0))) then 
                    indvar_flatten_fu_136 <= select_ln85_3_fu_399_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_136 <= ap_const_lv8_0;
                end if;
            end if; 
        end if;
    end process;

    tx_fu_128_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    tx_fu_128 <= ap_const_lv4_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    tx_fu_128 <= add_ln86_fu_497_p2;
                end if;
            end if; 
        end if;
    end process;

    ty_fu_132_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    ty_fu_132 <= ap_const_lv4_0;
                elsif ((ap_enable_reg_pp0_iter1 = ap_const_logic_1)) then 
                    ty_fu_132 <= select_ln85_fu_471_p3;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln89_reg_863 <= add_ln89_fu_612_p2;
                add_ln93_reg_877 <= add_ln93_fu_688_p2;
                add_ln95_3_reg_872 <= add_ln95_3_fu_679_p2;
                add_ln95_3_reg_872_pp0_iter10_reg <= add_ln95_3_reg_872_pp0_iter9_reg;
                add_ln95_3_reg_872_pp0_iter11_reg <= add_ln95_3_reg_872_pp0_iter10_reg;
                add_ln95_3_reg_872_pp0_iter12_reg <= add_ln95_3_reg_872_pp0_iter11_reg;
                add_ln95_3_reg_872_pp0_iter13_reg <= add_ln95_3_reg_872_pp0_iter12_reg;
                add_ln95_3_reg_872_pp0_iter4_reg <= add_ln95_3_reg_872;
                add_ln95_3_reg_872_pp0_iter5_reg <= add_ln95_3_reg_872_pp0_iter4_reg;
                add_ln95_3_reg_872_pp0_iter6_reg <= add_ln95_3_reg_872_pp0_iter5_reg;
                add_ln95_3_reg_872_pp0_iter7_reg <= add_ln95_3_reg_872_pp0_iter6_reg;
                add_ln95_3_reg_872_pp0_iter8_reg <= add_ln95_3_reg_872_pp0_iter7_reg;
                add_ln95_3_reg_872_pp0_iter9_reg <= add_ln95_3_reg_872_pp0_iter8_reg;
                and_ln92_reg_868 <= and_ln92_fu_623_p2;
                and_ln92_reg_868_pp0_iter10_reg <= and_ln92_reg_868_pp0_iter9_reg;
                and_ln92_reg_868_pp0_iter11_reg <= and_ln92_reg_868_pp0_iter10_reg;
                and_ln92_reg_868_pp0_iter12_reg <= and_ln92_reg_868_pp0_iter11_reg;
                and_ln92_reg_868_pp0_iter13_reg <= and_ln92_reg_868_pp0_iter12_reg;
                and_ln92_reg_868_pp0_iter3_reg <= and_ln92_reg_868;
                and_ln92_reg_868_pp0_iter4_reg <= and_ln92_reg_868_pp0_iter3_reg;
                and_ln92_reg_868_pp0_iter5_reg <= and_ln92_reg_868_pp0_iter4_reg;
                and_ln92_reg_868_pp0_iter6_reg <= and_ln92_reg_868_pp0_iter5_reg;
                and_ln92_reg_868_pp0_iter7_reg <= and_ln92_reg_868_pp0_iter6_reg;
                and_ln92_reg_868_pp0_iter8_reg <= and_ln92_reg_868_pp0_iter7_reg;
                and_ln92_reg_868_pp0_iter9_reg <= and_ln92_reg_868_pp0_iter8_reg;
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
                ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
                ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                gmem0_addr_reg_882 <= sext_ln93_fu_719_p1;
                icmp_ln84_reg_808_pp0_iter10_reg <= icmp_ln84_reg_808_pp0_iter9_reg;
                icmp_ln84_reg_808_pp0_iter11_reg <= icmp_ln84_reg_808_pp0_iter10_reg;
                icmp_ln84_reg_808_pp0_iter12_reg <= icmp_ln84_reg_808_pp0_iter11_reg;
                icmp_ln84_reg_808_pp0_iter13_reg <= icmp_ln84_reg_808_pp0_iter12_reg;
                icmp_ln84_reg_808_pp0_iter2_reg <= icmp_ln84_reg_808_pp0_iter1_reg;
                icmp_ln84_reg_808_pp0_iter3_reg <= icmp_ln84_reg_808_pp0_iter2_reg;
                icmp_ln84_reg_808_pp0_iter4_reg <= icmp_ln84_reg_808_pp0_iter3_reg;
                icmp_ln84_reg_808_pp0_iter5_reg <= icmp_ln84_reg_808_pp0_iter4_reg;
                icmp_ln84_reg_808_pp0_iter6_reg <= icmp_ln84_reg_808_pp0_iter5_reg;
                icmp_ln84_reg_808_pp0_iter7_reg <= icmp_ln84_reg_808_pp0_iter6_reg;
                icmp_ln84_reg_808_pp0_iter8_reg <= icmp_ln84_reg_808_pp0_iter7_reg;
                icmp_ln84_reg_808_pp0_iter9_reg <= icmp_ln84_reg_808_pp0_iter8_reg;
                select_ln84_3_reg_819_pp0_iter2_reg <= select_ln84_3_reg_819_pp0_iter1_reg;
                tmp_56_reg_858 <= mul_ln86_fu_587_p2(8 downto 6);
                tmp_reg_848 <= mul_ln85_fu_516_p2(8 downto 6);
                trunc_ln85_reg_888 <= trunc_ln85_fu_729_p1;
                trunc_ln85_reg_888_pp0_iter10_reg <= trunc_ln85_reg_888_pp0_iter9_reg;
                trunc_ln85_reg_888_pp0_iter11_reg <= trunc_ln85_reg_888_pp0_iter10_reg;
                trunc_ln85_reg_888_pp0_iter12_reg <= trunc_ln85_reg_888_pp0_iter11_reg;
                trunc_ln85_reg_888_pp0_iter13_reg <= trunc_ln85_reg_888_pp0_iter12_reg;
                trunc_ln85_reg_888_pp0_iter9_reg <= trunc_ln85_reg_888;
                trunc_ln86_reg_892 <= trunc_ln86_fu_733_p1;
                trunc_ln86_reg_892_pp0_iter10_reg <= trunc_ln86_reg_892_pp0_iter9_reg;
                trunc_ln86_reg_892_pp0_iter11_reg <= trunc_ln86_reg_892_pp0_iter10_reg;
                trunc_ln86_reg_892_pp0_iter12_reg <= trunc_ln86_reg_892_pp0_iter11_reg;
                trunc_ln86_reg_892_pp0_iter13_reg <= trunc_ln86_reg_892_pp0_iter12_reg;
                trunc_ln86_reg_892_pp0_iter9_reg <= trunc_ln86_reg_892;
                v_reg_896 <= m_axi_gmem0_RDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln84_reg_808 <= icmp_ln84_fu_354_p2;
                icmp_ln84_reg_808_pp0_iter1_reg <= icmp_ln84_reg_808;
                icmp_ln85_reg_812 <= icmp_ln85_fu_375_p2;
                select_ln84_3_reg_819 <= select_ln84_3_fu_381_p3;
                select_ln84_3_reg_819_pp0_iter1_reg <= select_ln84_3_reg_819;
                select_ln85_reg_837 <= select_ln85_fu_471_p3;
                tmp1_reg_843 <= tmp1_fu_485_p2;
                tx_mid2_reg_830 <= tx_mid2_fu_463_p3;
                    zext_ln73_cast_reg_803(8 downto 0) <= zext_ln73_cast_fu_319_p1(8 downto 0);
                    zext_ln84_cast_reg_798(8 downto 0) <= zext_ln84_cast_fu_315_p1(8 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter10_v_2_reg_295 <= ap_phi_reg_pp0_iter9_v_2_reg_295;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter11_v_2_reg_295 <= ap_phi_reg_pp0_iter10_v_2_reg_295;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter11 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter12_v_2_reg_295 <= ap_phi_reg_pp0_iter11_v_2_reg_295;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter12 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter13_v_2_reg_295 <= ap_phi_reg_pp0_iter12_v_2_reg_295;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter14_v_2_reg_295 <= ap_phi_reg_pp0_iter13_v_2_reg_295;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter1_v_2_reg_295 <= ap_phi_reg_pp0_iter0_v_2_reg_295;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter2_v_2_reg_295 <= ap_phi_reg_pp0_iter1_v_2_reg_295;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter3_v_2_reg_295 <= ap_phi_reg_pp0_iter2_v_2_reg_295;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter5_v_2_reg_295 <= ap_phi_reg_pp0_iter4_v_2_reg_295;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter6_v_2_reg_295 <= ap_phi_reg_pp0_iter5_v_2_reg_295;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter7_v_2_reg_295 <= ap_phi_reg_pp0_iter6_v_2_reg_295;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter8_v_2_reg_295 <= ap_phi_reg_pp0_iter7_v_2_reg_295;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter9_v_2_reg_295 <= ap_phi_reg_pp0_iter8_v_2_reg_295;
            end if;
        end if;
    end process;
    zext_ln84_cast_reg_798(9) <= '0';
    zext_ln73_cast_reg_803(9) <= '0';

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln84_3_fu_360_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten12_load) + unsigned(ap_const_lv8_1));
    add_ln84_fu_369_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_ic_load) + unsigned(ap_const_lv2_1));
    add_ln85_3_fu_393_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten_load) + unsigned(ap_const_lv8_1));
    add_ln85_fu_452_p2 <= std_logic_vector(unsigned(select_ln84_fu_428_p3) + unsigned(ap_const_lv4_1));
    add_ln86_fu_497_p2 <= std_logic_vector(unsigned(tx_mid2_fu_463_p3) + unsigned(ap_const_lv4_1));
    add_ln89_2_fu_603_p2 <= std_logic_vector(unsigned(tx_mid2_reg_830) + unsigned(ap_const_lv4_F));
    add_ln89_fu_612_p2 <= std_logic_vector(signed(sext_ln89_fu_608_p1) + signed(zext_ln84_cast_reg_798));
    add_ln93_2_fu_704_p2 <= std_logic_vector(unsigned(zext_ln93_2_fu_700_p1) + unsigned(input_r));
    add_ln93_fu_688_p0 <= grp_fu_749_p3;
    add_ln93_fu_688_p2 <= std_logic_vector(unsigned(add_ln93_fu_688_p0) + unsigned(zext_ln93_fu_685_p1));
    add_ln95_3_fu_679_p2 <= std_logic_vector(unsigned(sub_ln85_fu_670_p2) + unsigned(zext_ln95_10_fu_676_p1));
    add_ln95_fu_648_p2 <= std_logic_vector(unsigned(sub_ln95_fu_639_p2) + unsigned(zext_ln85_2_fu_645_p1));
    and_ln84_fu_446_p2 <= (xor_ln84_fu_435_p2 and icmp_ln86_fu_440_p2);
    and_ln92_fu_623_p2 <= (rev_fu_548_p2 and icmp_ln92_fu_617_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter13, ap_block_state6_io, ap_block_state14_pp0_stage0_iter13)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state14_pp0_stage0_iter13)) or ((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state6_io)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter13, ap_block_state6_io, ap_block_state14_pp0_stage0_iter13)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state14_pp0_stage0_iter13)) or ((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state6_io)));
    end process;


    ap_block_state14_pp0_stage0_iter13_assign_proc : process(m_axi_gmem0_RVALID, ap_predicate_op143_read_state14)
    begin
                ap_block_state14_pp0_stage0_iter13 <= ((ap_predicate_op143_read_state14 = ap_const_boolean_1) and (m_axi_gmem0_RVALID = ap_const_logic_0));
    end process;


    ap_block_state6_io_assign_proc : process(m_axi_gmem0_ARREADY, ap_predicate_op120_readreq_state6)
    begin
                ap_block_state6_io <= ((m_axi_gmem0_ARREADY = ap_const_logic_0) and (ap_predicate_op120_readreq_state6 = ap_const_boolean_1));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln84_fu_354_p2)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln84_fu_354_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter13_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter13_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14)
    begin
        if (((ap_enable_reg_pp0_iter14 = ap_const_logic_0) and (ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_phi_mux_v_2_phi_fu_299_p4_assign_proc : process(icmp_ln84_reg_808_pp0_iter13_reg, and_ln92_reg_868_pp0_iter13_reg, v_reg_896, ap_phi_reg_pp0_iter14_v_2_reg_295)
    begin
        if (((icmp_ln84_reg_808_pp0_iter13_reg = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln92_reg_868_pp0_iter13_reg))) then 
            ap_phi_mux_v_2_phi_fu_299_p4 <= v_reg_896;
        else 
            ap_phi_mux_v_2_phi_fu_299_p4 <= ap_phi_reg_pp0_iter14_v_2_reg_295;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_v_2_reg_295 <= "XXXXXXXXXXXXXXXX";

    ap_predicate_op120_readreq_state6_assign_proc : process(icmp_ln84_reg_808_pp0_iter4_reg, and_ln92_reg_868_pp0_iter4_reg)
    begin
                ap_predicate_op120_readreq_state6 <= ((ap_const_lv1_1 = and_ln92_reg_868_pp0_iter4_reg) and (icmp_ln84_reg_808_pp0_iter4_reg = ap_const_lv1_0));
    end process;


    ap_predicate_op143_read_state14_assign_proc : process(icmp_ln84_reg_808_pp0_iter12_reg, and_ln92_reg_868_pp0_iter12_reg)
    begin
                ap_predicate_op143_read_state14 <= ((icmp_ln84_reg_808_pp0_iter12_reg = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln92_reg_868_pp0_iter12_reg));
    end process;

    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_ic_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, ic_fu_140)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_ic_load <= ap_const_lv2_0;
        else 
            ap_sig_allocacmp_ic_load <= ic_fu_140;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten12_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten12_fu_144)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten12_load <= ap_const_lv8_0;
        else 
            ap_sig_allocacmp_indvar_flatten12_load <= indvar_flatten12_fu_144;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten_fu_136)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten_load <= ap_const_lv8_0;
        else 
            ap_sig_allocacmp_indvar_flatten_load <= indvar_flatten_fu_136;
        end if; 
    end process;

    empty_104_fu_535_p2 <= std_logic_vector(signed(tmp1_cast_fu_532_p1) + signed(zext_ln73_cast_reg_803));
    empty_fu_458_p2 <= (icmp_ln85_reg_812 or and_ln84_fu_446_p2);

    gmem0_blk_n_AR_assign_proc : process(ap_enable_reg_pp0_iter5, m_axi_gmem0_ARREADY, ap_predicate_op120_readreq_state6, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op120_readreq_state6 = ap_const_boolean_1))) then 
            gmem0_blk_n_AR <= m_axi_gmem0_ARREADY;
        else 
            gmem0_blk_n_AR <= ap_const_logic_1;
        end if; 
    end process;


    gmem0_blk_n_R_assign_proc : process(ap_enable_reg_pp0_iter13, m_axi_gmem0_RVALID, ap_predicate_op143_read_state14, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_predicate_op143_read_state14 = ap_const_boolean_1))) then 
            gmem0_blk_n_R <= m_axi_gmem0_RVALID;
        else 
            gmem0_blk_n_R <= ap_const_logic_1;
        end if; 
    end process;


    grp_fu_479_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            grp_fu_479_ce <= ap_const_logic_1;
        else 
            grp_fu_479_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_479_p1 <= ap_const_lv4_3(3 - 1 downto 0);

    grp_fu_491_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            grp_fu_491_ce <= ap_const_logic_1;
        else 
            grp_fu_491_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_491_p1 <= ap_const_lv4_3(3 - 1 downto 0);

    grp_fu_749_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            grp_fu_749_ce <= ap_const_logic_1;
        else 
            grp_fu_749_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_749_p0 <= ap_const_lv19_19000(17 - 1 downto 0);
    grp_fu_749_p1 <= grp_fu_749_p10(2 - 1 downto 0);
    grp_fu_749_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln84_3_fu_381_p3),19));
    grp_fu_749_p2 <= std_logic_vector(signed(p_shl_fu_562_p1) + signed(p_shl21_fu_574_p1));
    icmp_ln84_fu_354_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten12_load = ap_const_lv8_F3) else "0";
    icmp_ln85_fu_375_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten_load = ap_const_lv8_51) else "0";
    icmp_ln86_fu_440_p2 <= "1" when (tx_fu_128 = ap_const_lv4_9) else "0";
    icmp_ln92_fu_617_p2 <= "1" when (unsigned(add_ln89_fu_612_p2) < unsigned(ap_const_lv10_140)) else "0";
    input_tile_10_address0 <= zext_ln95_11_fu_737_p1(5 - 1 downto 0);
    input_tile_10_ce0 <= input_tile_10_ce0_local;

    input_tile_10_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            input_tile_10_ce0_local <= ap_const_logic_1;
        else 
            input_tile_10_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    input_tile_10_d0 <= ap_phi_mux_v_2_phi_fu_299_p4;
    input_tile_10_we0 <= input_tile_10_we0_local;

    input_tile_10_we0_local_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001, trunc_ln85_reg_888_pp0_iter13_reg, trunc_ln86_reg_892_pp0_iter13_reg)
    begin
        if ((not((trunc_ln86_reg_892_pp0_iter13_reg = ap_const_lv2_0)) and not((trunc_ln86_reg_892_pp0_iter13_reg = ap_const_lv2_1)) and (ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (trunc_ln85_reg_888_pp0_iter13_reg = ap_const_lv2_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            input_tile_10_we0_local <= ap_const_logic_1;
        else 
            input_tile_10_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    input_tile_11_address0 <= zext_ln95_11_fu_737_p1(5 - 1 downto 0);
    input_tile_11_ce0 <= input_tile_11_ce0_local;

    input_tile_11_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            input_tile_11_ce0_local <= ap_const_logic_1;
        else 
            input_tile_11_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    input_tile_11_d0 <= ap_phi_mux_v_2_phi_fu_299_p4;
    input_tile_11_we0 <= input_tile_11_we0_local;

    input_tile_11_we0_local_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001, trunc_ln85_reg_888_pp0_iter13_reg, trunc_ln86_reg_892_pp0_iter13_reg)
    begin
        if (((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (trunc_ln86_reg_892_pp0_iter13_reg = ap_const_lv2_0) and (trunc_ln85_reg_888_pp0_iter13_reg = ap_const_lv2_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            input_tile_11_we0_local <= ap_const_logic_1;
        else 
            input_tile_11_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    input_tile_12_address0 <= zext_ln95_11_fu_737_p1(5 - 1 downto 0);
    input_tile_12_ce0 <= input_tile_12_ce0_local;

    input_tile_12_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            input_tile_12_ce0_local <= ap_const_logic_1;
        else 
            input_tile_12_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    input_tile_12_d0 <= ap_phi_mux_v_2_phi_fu_299_p4;
    input_tile_12_we0 <= input_tile_12_we0_local;

    input_tile_12_we0_local_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001, trunc_ln85_reg_888_pp0_iter13_reg, trunc_ln86_reg_892_pp0_iter13_reg)
    begin
        if (((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (trunc_ln86_reg_892_pp0_iter13_reg = ap_const_lv2_1) and (trunc_ln85_reg_888_pp0_iter13_reg = ap_const_lv2_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            input_tile_12_we0_local <= ap_const_logic_1;
        else 
            input_tile_12_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    input_tile_13_address0 <= zext_ln95_11_fu_737_p1(5 - 1 downto 0);
    input_tile_13_ce0 <= input_tile_13_ce0_local;

    input_tile_13_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            input_tile_13_ce0_local <= ap_const_logic_1;
        else 
            input_tile_13_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    input_tile_13_d0 <= ap_phi_mux_v_2_phi_fu_299_p4;
    input_tile_13_we0 <= input_tile_13_we0_local;

    input_tile_13_we0_local_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001, trunc_ln85_reg_888_pp0_iter13_reg, trunc_ln86_reg_892_pp0_iter13_reg)
    begin
        if ((not((trunc_ln86_reg_892_pp0_iter13_reg = ap_const_lv2_0)) and not((trunc_ln86_reg_892_pp0_iter13_reg = ap_const_lv2_1)) and (ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (trunc_ln85_reg_888_pp0_iter13_reg = ap_const_lv2_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            input_tile_13_we0_local <= ap_const_logic_1;
        else 
            input_tile_13_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    input_tile_14_address0 <= zext_ln95_11_fu_737_p1(5 - 1 downto 0);
    input_tile_14_ce0 <= input_tile_14_ce0_local;

    input_tile_14_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            input_tile_14_ce0_local <= ap_const_logic_1;
        else 
            input_tile_14_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    input_tile_14_d0 <= ap_phi_mux_v_2_phi_fu_299_p4;
    input_tile_14_we0 <= input_tile_14_we0_local;

    input_tile_14_we0_local_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001, trunc_ln85_reg_888_pp0_iter13_reg, trunc_ln86_reg_892_pp0_iter13_reg)
    begin
        if ((not((trunc_ln85_reg_888_pp0_iter13_reg = ap_const_lv2_0)) and not((trunc_ln85_reg_888_pp0_iter13_reg = ap_const_lv2_1)) and (ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (trunc_ln86_reg_892_pp0_iter13_reg = ap_const_lv2_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            input_tile_14_we0_local <= ap_const_logic_1;
        else 
            input_tile_14_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    input_tile_15_address0 <= zext_ln95_11_fu_737_p1(5 - 1 downto 0);
    input_tile_15_ce0 <= input_tile_15_ce0_local;

    input_tile_15_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            input_tile_15_ce0_local <= ap_const_logic_1;
        else 
            input_tile_15_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    input_tile_15_d0 <= ap_phi_mux_v_2_phi_fu_299_p4;
    input_tile_15_we0 <= input_tile_15_we0_local;

    input_tile_15_we0_local_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001, trunc_ln85_reg_888_pp0_iter13_reg, trunc_ln86_reg_892_pp0_iter13_reg)
    begin
        if ((not((trunc_ln85_reg_888_pp0_iter13_reg = ap_const_lv2_0)) and not((trunc_ln85_reg_888_pp0_iter13_reg = ap_const_lv2_1)) and (ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (trunc_ln86_reg_892_pp0_iter13_reg = ap_const_lv2_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            input_tile_15_we0_local <= ap_const_logic_1;
        else 
            input_tile_15_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    input_tile_16_address0 <= zext_ln95_11_fu_737_p1(5 - 1 downto 0);
    input_tile_16_ce0 <= input_tile_16_ce0_local;

    input_tile_16_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            input_tile_16_ce0_local <= ap_const_logic_1;
        else 
            input_tile_16_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    input_tile_16_d0 <= ap_phi_mux_v_2_phi_fu_299_p4;
    input_tile_16_we0 <= input_tile_16_we0_local;

    input_tile_16_we0_local_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001, trunc_ln85_reg_888_pp0_iter13_reg, trunc_ln86_reg_892_pp0_iter13_reg)
    begin
        if ((not((trunc_ln85_reg_888_pp0_iter13_reg = ap_const_lv2_0)) and not((trunc_ln86_reg_892_pp0_iter13_reg = ap_const_lv2_0)) and not((trunc_ln86_reg_892_pp0_iter13_reg = ap_const_lv2_1)) and not((trunc_ln85_reg_888_pp0_iter13_reg = ap_const_lv2_1)) and (ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            input_tile_16_we0_local <= ap_const_logic_1;
        else 
            input_tile_16_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    input_tile_9_address0 <= zext_ln95_11_fu_737_p1(5 - 1 downto 0);
    input_tile_9_ce0 <= input_tile_9_ce0_local;

    input_tile_9_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            input_tile_9_ce0_local <= ap_const_logic_1;
        else 
            input_tile_9_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    input_tile_9_d0 <= ap_phi_mux_v_2_phi_fu_299_p4;
    input_tile_9_we0 <= input_tile_9_we0_local;

    input_tile_9_we0_local_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001, trunc_ln85_reg_888_pp0_iter13_reg, trunc_ln86_reg_892_pp0_iter13_reg)
    begin
        if (((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (trunc_ln86_reg_892_pp0_iter13_reg = ap_const_lv2_1) and (trunc_ln85_reg_888_pp0_iter13_reg = ap_const_lv2_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            input_tile_9_we0_local <= ap_const_logic_1;
        else 
            input_tile_9_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    input_tile_address0 <= zext_ln95_11_fu_737_p1(5 - 1 downto 0);
    input_tile_ce0 <= input_tile_ce0_local;

    input_tile_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            input_tile_ce0_local <= ap_const_logic_1;
        else 
            input_tile_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    input_tile_d0 <= ap_phi_mux_v_2_phi_fu_299_p4;
    input_tile_we0 <= input_tile_we0_local;

    input_tile_we0_local_assign_proc : process(ap_enable_reg_pp0_iter14, ap_block_pp0_stage0_11001, trunc_ln85_reg_888_pp0_iter13_reg, trunc_ln86_reg_892_pp0_iter13_reg)
    begin
        if (((ap_enable_reg_pp0_iter14 = ap_const_logic_1) and (trunc_ln86_reg_892_pp0_iter13_reg = ap_const_lv2_0) and (trunc_ln85_reg_888_pp0_iter13_reg = ap_const_lv2_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            input_tile_we0_local <= ap_const_logic_1;
        else 
            input_tile_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem0_ARADDR <= gmem0_addr_reg_882;
    m_axi_gmem0_ARBURST <= ap_const_lv2_0;
    m_axi_gmem0_ARCACHE <= ap_const_lv4_0;
    m_axi_gmem0_ARID <= ap_const_lv1_0;
    m_axi_gmem0_ARLEN <= ap_const_lv64_1(32 - 1 downto 0);
    m_axi_gmem0_ARLOCK <= ap_const_lv2_0;
    m_axi_gmem0_ARPROT <= ap_const_lv3_0;
    m_axi_gmem0_ARQOS <= ap_const_lv4_0;
    m_axi_gmem0_ARREGION <= ap_const_lv4_0;
    m_axi_gmem0_ARSIZE <= ap_const_lv3_0;
    m_axi_gmem0_ARUSER <= ap_const_lv1_0;

    m_axi_gmem0_ARVALID_assign_proc : process(ap_enable_reg_pp0_iter5, ap_predicate_op120_readreq_state6, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter5 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op120_readreq_state6 = ap_const_boolean_1))) then 
            m_axi_gmem0_ARVALID <= ap_const_logic_1;
        else 
            m_axi_gmem0_ARVALID <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem0_AWADDR <= ap_const_lv64_0;
    m_axi_gmem0_AWBURST <= ap_const_lv2_0;
    m_axi_gmem0_AWCACHE <= ap_const_lv4_0;
    m_axi_gmem0_AWID <= ap_const_lv1_0;
    m_axi_gmem0_AWLEN <= ap_const_lv32_0;
    m_axi_gmem0_AWLOCK <= ap_const_lv2_0;
    m_axi_gmem0_AWPROT <= ap_const_lv3_0;
    m_axi_gmem0_AWQOS <= ap_const_lv4_0;
    m_axi_gmem0_AWREGION <= ap_const_lv4_0;
    m_axi_gmem0_AWSIZE <= ap_const_lv3_0;
    m_axi_gmem0_AWUSER <= ap_const_lv1_0;
    m_axi_gmem0_AWVALID <= ap_const_logic_0;
    m_axi_gmem0_BREADY <= ap_const_logic_0;

    m_axi_gmem0_RREADY_assign_proc : process(ap_enable_reg_pp0_iter13, ap_predicate_op143_read_state14, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_predicate_op143_read_state14 = ap_const_boolean_1))) then 
            m_axi_gmem0_RREADY <= ap_const_logic_1;
        else 
            m_axi_gmem0_RREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_gmem0_WDATA <= ap_const_lv16_0;
    m_axi_gmem0_WID <= ap_const_lv1_0;
    m_axi_gmem0_WLAST <= ap_const_logic_0;
    m_axi_gmem0_WSTRB <= ap_const_lv2_0;
    m_axi_gmem0_WUSER <= ap_const_lv1_0;
    m_axi_gmem0_WVALID <= ap_const_logic_0;
    mul_ln85_fu_516_p0 <= mul_ln85_fu_516_p00(4 - 1 downto 0);
    mul_ln85_fu_516_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln85_reg_837),9));
    mul_ln85_fu_516_p1 <= ap_const_lv9_16(6 - 1 downto 0);
    mul_ln86_fu_587_p0 <= mul_ln86_fu_587_p00(4 - 1 downto 0);
    mul_ln86_fu_587_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tx_mid2_reg_830),9));
    mul_ln86_fu_587_p1 <= ap_const_lv9_16(6 - 1 downto 0);
        p_shl21_fu_574_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_55_fu_566_p3),19));

    p_shl3_fu_632_p3 <= (select_ln84_3_reg_819_pp0_iter2_reg & ap_const_lv2_0);
        p_shl_fu_562_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_54_fu_554_p3),19));

    rev_fu_548_p2 <= (tmp_53_fu_540_p3 xor ap_const_lv1_1);
    select_ln84_3_fu_381_p3 <= 
        add_ln84_fu_369_p2 when (icmp_ln85_fu_375_p2(0) = '1') else 
        ap_sig_allocacmp_ic_load;
    select_ln84_fu_428_p3 <= 
        ap_const_lv4_0 when (icmp_ln85_reg_812(0) = '1') else 
        ty_fu_132;
    select_ln85_3_fu_399_p3 <= 
        ap_const_lv8_1 when (icmp_ln85_fu_375_p2(0) = '1') else 
        add_ln85_3_fu_393_p2;
    select_ln85_fu_471_p3 <= 
        add_ln85_fu_452_p2 when (and_ln84_fu_446_p2(0) = '1') else 
        select_ln84_fu_428_p3;
        sext_ln89_fu_608_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln89_2_fu_603_p2),10));

        sext_ln93_fu_719_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln_fu_709_p4),64));

    shl_ln_fu_693_p3 <= (add_ln93_reg_877 & ap_const_lv1_0);
    sub_ln85_fu_670_p2 <= std_logic_vector(unsigned(tmp_52_fu_658_p3) - unsigned(zext_ln95_9_fu_666_p1));
    sub_ln95_fu_639_p2 <= std_logic_vector(unsigned(p_shl3_fu_632_p3) - unsigned(zext_ln95_fu_629_p1));
        tmp1_cast_fu_532_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp1_reg_843),10));

    tmp1_fu_485_p2 <= std_logic_vector(unsigned(select_ln85_fu_471_p3) + unsigned(ap_const_lv4_F));
    tmp_52_fu_658_p3 <= (trunc_ln95_fu_654_p1 & ap_const_lv2_0);
    tmp_53_fu_540_p3 <= empty_104_fu_535_p2(9 downto 9);
    tmp_54_fu_554_p3 <= (empty_104_fu_535_p2 & ap_const_lv8_0);
    tmp_55_fu_566_p3 <= (empty_104_fu_535_p2 & ap_const_lv6_0);
    trunc_ln85_fu_729_p1 <= grp_fu_479_p2(2 - 1 downto 0);
    trunc_ln86_fu_733_p1 <= grp_fu_491_p2(2 - 1 downto 0);
    trunc_ln95_fu_654_p1 <= add_ln95_fu_648_p2(3 - 1 downto 0);
    trunc_ln_fu_709_p4 <= add_ln93_2_fu_704_p2(63 downto 1);
    tx_mid2_fu_463_p3 <= 
        ap_const_lv4_0 when (empty_fu_458_p2(0) = '1') else 
        tx_fu_128;
    xor_ln84_fu_435_p2 <= (icmp_ln85_reg_812 xor ap_const_lv1_1);
    zext_ln73_cast_fu_319_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln73),10));
    zext_ln84_cast_fu_315_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln84),10));
    zext_ln85_2_fu_645_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_reg_848),4));
    zext_ln93_2_fu_700_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_693_p3),64));
    zext_ln93_fu_685_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln89_reg_863),19));
    zext_ln95_10_fu_676_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_56_reg_858),5));
    zext_ln95_11_fu_737_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln95_3_reg_872_pp0_iter13_reg),64));
    zext_ln95_9_fu_666_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln95_fu_648_p2),5));
    zext_ln95_fu_629_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln84_3_reg_819_pp0_iter2_reg),4));
end behav;
